// Default Data Structure matching 'Requirement gathering.md'
// --- Cryptographic Helper Functions (Web Crypto API) ---
const encoder = new TextEncoder();
const decoder = new TextDecoder();
const FIXED_SALT = encoder.encode("MRP_ERP_Requirement_Gathering_Salt_2026");

function arrayBufferToBase64(buffer) {
    let binary = '';
    const bytes = new Uint8Array(buffer);
    const len = bytes.byteLength;
    for (let i = 0; i < len; i++) {
        binary += String.fromCharCode(bytes[i]);
    }
    return window.btoa(binary);
}

function base64ToArrayBuffer(base64) {
    const binary_string = window.atob(base64);
    const len = binary_string.length;
    const bytes = new Uint8Array(len);
    for (let i = 0; i < len; i++) {
        bytes[i] = binary_string.charCodeAt(i);
    }
    return bytes.buffer;
}

async function deriveMasterKey(password) {
    const passwordKey = await window.crypto.subtle.importKey(
        "raw",
        encoder.encode(password),
        { name: "PBKDF2" },
        false,
        ["deriveKey"]
    );
    return window.crypto.subtle.deriveKey(
        {
            name: "PBKDF2",
            salt: FIXED_SALT,
            iterations: 100000,
            hash: "SHA-256"
        },
        passwordKey,
        { name: "AES-GCM", length: 256 },
        false,
        ["encrypt", "decrypt"]
    );
}

async function encryptWithKey(plaintext, cryptoKey) {
    const plaintextBytes = encoder.encode(plaintext);
    const iv = window.crypto.getRandomValues(new Uint8Array(12));

    const ciphertextBuffer = await window.crypto.subtle.encrypt(
        {
            name: "AES-GCM",
            iv: iv
        },
        cryptoKey,
        plaintextBytes
    );

    const ciphertextBytes = new Uint8Array(ciphertextBuffer);
    const packagedBytes = new Uint8Array(iv.length + ciphertextBytes.length);
    packagedBytes.set(iv, 0);
    packagedBytes.set(ciphertextBytes, iv.length);

    return arrayBufferToBase64(packagedBytes.buffer);
}

async function decryptWithKey(encryptedBase64, cryptoKey) {
    try {
        const encryptedBytes = new Uint8Array(base64ToArrayBuffer(encryptedBase64));
        if (encryptedBytes.length < 12) {
            throw new Error("Invalid cipher data: too short");
        }
        const iv = encryptedBytes.slice(0, 12);
        const ciphertext = encryptedBytes.slice(12);

        const decryptedBuffer = await window.crypto.subtle.decrypt(
            {
                name: "AES-GCM",
                iv: iv
            },
            cryptoKey,
            ciphertext
        );

        return decoder.decode(decryptedBuffer);
    } catch (e) {
        console.error("Decryption failed", e);
        throw e;
    }
}

const ENCRYPTED_DEFAULT_MODULES = "EDi9SXje2jOYUKtbfOWgt7NXOUlvavNLwkTylL+tdnn9mQcMMLuaZWy8UlqDrG1Jz7En/BaMeQ+Yixqe8WGY0UQ3np6eSzsQB0KbHdBGYFiuuTfl0sIYeJTq5FRNQO1Cey/VfPR71ZMIMF4lxn9ngneliErXbPgescHbTduTCpjOsJyxvUHwun5lrzqvkuEJWW3hOXFW1zCsRLRHffOkhK72MzbAfSFKzjVFdOjygJypIPW+dHugQVug6ucqSrYqxYuZxCI4RDL5S6B4U7ez9jnNpXZbWEYRk9Jx2luF5AK2WPDlQG1DbRpJpZbveOfBZOfH7ywNHZHRSjuW2aeeNMrIxhDDF/uSdshJnW1LvBKn5w13HkFYWpfzox9XXHtKLMjhQFprq2MCqwu09OlD+xqKJ2wpW6MwCajKiAEMMVbgQMwUKnZJUFdxd898ZH7byNYxrkJO9CkY1rBEFflqAzr2QICgop1ILRzBjAmT9Y/SrEFrUffw80VOED3blsnp49/K+HTp4trInFRRknPaRGyhDuphi5LRPHiFXNc4euyKRyofthYU9UfJEIUAnSji2Htd147J1MMX9KieKJ2rIuY20leGUgzGzWjDbj9ag6Tj79x4FhUz0A7zyTKjZt2DrcjvxM9djNK1JkNC6e9nbW33MjrsEsyKXwPBPRnarf8doN4mzCxmjTOzQPo4JoChonRlhrbyHqSyf7FwPsZx1MaUgxVDtDKJvpY9bJQGWQ5yd7DctLwnuG3RWYXpAyfCGUENTiJvGS9ZrNXu7ho8ZRrzO/WC23c3EQeZB644cyoL8XR0rfYv2fnltvWgbX43ITWFClfvGsrLwv8jG0oFzw4++lvUo4b0bF58BtHFUQ+D3IfrWBfLsY1DF4wi7TUxUJu1JL2+fpvuLPpveRZVxYqcmlLff82awkddvqgep/6qO+l0PgNaqqYPHe9J8ThRlYDS3oX5XQr/2xQWPQCnYZAxPcFQny6RAmsIQ91Nqi2/uRbTDlwHt3vxxohBabFEBNeGWOA5pvcl0+T2K6Lhra+BdL+KVumoINDvz0yCri/dpxP81A/rXSAEUJkD/as3/DDT2v5bBYgl1gq9QmPmfbok5hYaTvE6TvuH6QfdoVLyBO9HPzreB1s38ESJColJt6Hj1fPL7BcjT5TVAJmVat8gClmYNPyiOLhLFd4u5S4UF79AlNS9GCxNKov4F79TLDLB2yl9aSKChudfbC04jDiRdd11fq1h2B/WSKQ8RT33ZzWSEzI2ta/aQl8VPqjgn55vCIIGvUu9u+FrvTT6noh9PvG61e6pHIlAo0RuEldBrtovfBl2WVm8WIeIAGxI6FdKEdDALguuoktNylsPfcx6MqZSFVtTF7QT10vJEjKRUB1GdrFeRWGCtPCvSjoxaxHsyTRl2UkCVopQmTXt/xyOGO4M4MSC3JdaiyY6TMQ2M8OQfTcouXm3oLkrYc/kum2QkF7FS86LsGsbmZGmYbZmeyLFm+LgRT1ZF/DiJowQl+jLeFaauP28aK+pbT+UOp4yGrAKLeJUXPlQ4FnZl6fARSi70XhwLyeznfdNvu7gIMsH362BV3m72YJig6K43ekbIVEShAv99xwlLZ0iLwRyqYZMbQMKlRAEUcI3pHLG3Z8zrueRbdLZo0iUObh9t4rfS0VfD2GSQGPK2l+ZO8Itive6sztcnUUs/fy41fh7cVuoCBYQ0Ou7hMYWr3JvdGXFMWZgKaqKG5tm2iKHa5ILVcAAi/IXBrmlb2gfXhq8GsrZCZ+aB+NiQS3EXdkljWvs+2ccaIuxlPUEX7YiCr4SpZPwTXxjf38o6ZtzaRu+v3Itn3NuQXigFpQTxxTuE+b6Ghp0kufUHIXZw9hyAKCF7KItBDjHrvZ/+v7GNVQ8YeRfUGGrzJY8Qb5D52gOpe5x20iw41A6hhmVZh6j5pTGkV7Jd1MVX8TZmuKclT5WTCRKpRnKCI0/G24ujO0pQA2/EGdWVBoELarkjTih6XE8787sbeetoj2FRuThPMVWsWeJ3c09cgSwyDlX3LQDANg9rFBWdfq6FunjCVT4eYdQIjt4jrIqO0jo77TdUm/l88Q+F410WEssX9X3r/5BbL8F4SFZlEJrhJqVQSSHcqlDcxLQHPwgwCPISLIaLnmAjQkDGwbPqxyoVptN2F4fY3gjX0gOIibPYxY5pB+MnTvH9T5Pe7FrmjghTHNDHWRgJPkFaNLVpkZabU6AxVfCrptPvLAnXwW0eDaJcmTtHzusXr/YxLPexVSewSUbi8w31fXXWqwkGe8VeCF7RcvBSCm53XyuhSkw94zfq7MX3ufE4SnOrILUHY1FTSH+afTQvFHpcgSjXBQtZntGpoTcJwINeGSaEITZONYS0yKm3FNvjgFmCxqEXTVNlPLr+l1nogBGmDeXsG4ZmJTahQW77F44AK1yc5LGxfeUE3domv98BJLpVND/AwXIElq3hxZo+nEpw2RlcqJt+zwcV3P44e4OYL4/coCZUAr8Yb6zrhuVR1UPhOEFycYB952Cnfs0GOi94HamNV+0uBtI4NVQ62hvgVq4cxoCcGmnfb8PP+2HoXp3QyKGrOK4fpz58bff7MC33b0zA4T7YC3w9ksSNfQpQay05Xl9spXz646gP3sslLscNDKnz1dt0BPFZGiJB8BQPKtyFWCpQoBXIQVQh7RzF+t6mZdkEyrKaAXQ0VZ7eU+IkNKzSraWJC9j5u+OKg7GPl+okMvAHDtB1klGNInpCPDLeAgyGME+GhiSEsY6gkt6zLDY6fruqMtGCGve3zkO2bmyabvFhoOJ4pPTJ76jdKHJidKCILh2WhyQyrpcNn6TQkHQalxg2NAnqGfTx6KgZWguwd1mZEqvyu0ebqbiFUdQrHER3GsfOTigMuMEq5ru3a0jmqTtfQaEQL06KskYVnOwZZ3nqtxTZADrnoON7P6YCisuHDo/MMIfFX8HrpT3+e4Y1jvjIVDgG36MjV31R15NimYca0YevXSfRspH4mnJKdLXiNehfCLHenrq6t8UXdbrSocT91fbA5pdUJi6Q//c7KT9soexKzM8go56tzPw48BoSqNsEJBcpVJpKvN3mIcPMQWuQTvJkXwI6ehk0X0JKaoNfo6HQyQWdkY+D92V6syphkkAxqW2hc3v6u3E4LfV0owLMBAZzW0uoCvMtt/RH2YDYMdP9TZ0IKEIf3b1G4GJhgB5gV7UNv3GvWiRLyatcRu02A7LeSsYyd8CAgtUxfYk6hc3aoLjRPBeuX+aZRK4APzgmz76FuFZJ5lcnTdAlU9/dGO8vd68sNLiblN7lXMLKm+wsYFtGsBr0f+t9Zq5bPgv4sDentDVj5wotD5pf/mGOzajR40naf1pxeCFU9IWB2WzyMZDhNd8VZ+x847U2CaAEqCjQoec8SGr8chkax9U/eDzt2b2/5sVjKKkYeI3SuJx8q2LZUEUqPgZndqgGvMqx9kUITNEZPYiUtVEDqmCBCj8L+5l6YTqROe26Ac+nbPzeSpzxycPwG+i2JIUYQ/8XQXErDrXAPAS4k0RDGu6XMD/1ePdrW4TMsmU9gjHdFaixWWgZSU1x/b5kriCe/B4xwwtXTuhF7vZWYswIjUBLPcdgsP4TKreHHIJtFeOA4AhEpwq7lKKcrSewHAc2gbfP3n1xYSCaZ7/88tDwaH7o8Uo3YZf7heLQMQwJFba80K6plPrhUM0+Ytjl8L+BHjzd3UGc+bVALWxZDov2gZkfLqEs7yaEqr/LWGlxOrXfsWIpGq0XMLJvcd72KjAXsumULVrbYQwaRqHKSq0ugmD351jKev28voW7ktWEHydsSIABPYTXi5ez4r617jYVziOxqZ/ZCsKCJ1HhOOijpeZsCycn5DUGXLH1TXBuKBdxg8OXi2Jb4p9vp2SfeUK73YNnpdBcvhc6XfUsDl9jmVlT1PNkB34SWval44NgjPrmR+6L6TiuQDLvg6iDFEpeLrd5XkDZT9+v++UmmBVYZBCJxn9vuVwLFzqzXFOzb0WVTZwjOOLlJ62ZIVmAVQiPdgX4rWI4or0GAivnFvjl/we1E2O4D2byt9k0+r+MRQqSVwmnB3rtJOUKrlpdFCCJFyt4bJfw1dq9VqwO5QeU0XURrEE2NXM7aTOFradJRA2fRxQOMFH471Sib8/yAlerjbjPbjenb1HGoU7KFkT+U5Vr31D1DObG5vKrKrE2WT+zbmYvmSonLykWMNNtEETaRMjb6V+j3fQTMdjkb7qYVZGkAzxUowWAE/WGtMDLXlHyMtd77vyAkfuG+WuBhfJr8nlGzKf1CTZxV6WtVreFFQGczsbCXVOW4hJheSqZXu5W8vtHBV8FvckfMLULJKYao6KPefHsEdb68o78zlCy1tUCQsJ8hmizS7zy2lpG+ek7StUvsGnQkQqF3ipUCdqME0rIwBnyNNyL1RcWxhZkIy73C/wCrrjqMFGS7noMeXJ6QcXMl0/axLcx/skJV4156r0KsgzvSNKUjS9T+RPW8dBz7Shri1CWqQDzEMaly6HkEtQJj0PTkh3Xica+VJA2VT1NdyiSHARAE0z5gXqgO11k3vESFRKtxwNYAEmaCCFQ/843RLK6PGKGoa0K+wfu6cFDS+jrdau5G2fESoJog7RXpNxKJ4ozRtFvwmtn4JdOIvNPBEfz09TASH58sAeD4bp1J+lwwm8kiAdKS5OII9xwtKVg/nWouAps4e2VRFsn376jhKvGmDJWxM9YKgnK2BWss9zv8RCtmA74B7eTejeEwosEjULo+9IIPYxU9P4gqgg3FC4Hwes+HQujqwFvijoU0dxffykhxn+phnODgYj+lhV4p7HOB/hNIpTwAbyYgQMWUaoXMuADV6WV6DsCBr8Wm1Df2vphiEs8q+/bFqyNJVvrLBq9ocn4n1D3bGVXU5gvQ2wYsKVDreZzn3QLi9zYNjyk5j4e/8tcVh903mkc/AgbFSkoxoX0vF8Yd+ocC51Y73Fv0lqWn3W/MVEzLAVpRzH4gtoegJwoqIf6q2tSMi/Raxzt4KxdAnnV0KS10wkALBaiGGZdvULFWcXwzLoYVA2uRTwyv2XmFYwqLEJwY1UEMjGWhEhnI1M2yHxNKaW1fGSbj0T2qMMlq3newomEiYEV0ErHLu6CCHIiBbBqrFTFAHYg8wo7YYBtohbQtgUfFumbwIyfPxxa9WaJyMOyNVccsNfPpvQ8ThqxepdWDYfLvrK6AALBws/5ISqeaJSv3D4QKmz/PGoalEOpSldCezqlp093mWa+ptWuogBKmiHRli+QydwHoMvCX7cRwf4p5Axh9poNKFoKJrQ221awIs2z57SBOkX5xTNLWp5dMQ86S2YDd122zco/eRFRwgOSFe2FJKSdRt6EKAlifMtMmvt4jXDT8K6b6FdTwSoiiCZtvtyGNi5IMp8SsnoHD4DSQ7Rgxx5RckwtX5Qzr85MUeiCvzrBLhQyiO/xGDOtYFF6zqzVE7NFE3DkMTmYvWn8VqNiOoakRucaKz5PNDp4RGfrn6Km0jLm5B/Ggwu3699czlwTRISQ/BSVL4AIJ52nWa7zMvoewQU78WEDNipFT5y+Zx4M2Ar/cs8havPn1G8gcUYRMmfh3sET/2Z3kkpOBCuxrqzz7Mze7vLxtWH1lNdSAI4rSDSVxQW5fnMyQ1vAqwxUmirNjfr4hVRj7lXiSGeMLla6igFjM8JQ8aBX4pQmz6Pngk9NJaUzfaMQh4C+p7D29I19/o7URvTyBN3ZZYK2IvrrPVhU3ZJb7RQV6dij/2ajRz2w98yrfN1iYXKRxKTF1MTWNINqRQs1w6+gPGzVYEl3AQjUlJHcFRjHM3u577BKXSJgp+MMEbg8BFGz1Qzle58x+IMEi1DwDIvSvwra9mqyO9kXJG3PbpL00EgopXLs8ODAGcrKTZStGpI8gMpdG/HV1wmPdA0lfRfE1T4Ut6wQxWEnS85owwb8osMy+qxCL/TR+UE7GH8XbnY6Xh60e0SY04EoLKBNRhT28wnT9iBTPY4Cix4DmCkCHJiMFV4QxLuQLubj19vvPYmgcuZ/i8poJHTN4rscTF7N2hhQtaKciUutgv1HO70+cANS2Hyb3so+3HzBpsbxYzgJ+QRjSkaZlj38bkeeGX3IFSJ2bJMrIkr7qEm8DXh0FjU3DyuKuSVUTPKjewnvIkkEPJscF6mtY1ou4MUkto0OoxcEb+9UlFKtsA5IOsIFOjOJ9NEfAIM0nnrAIFwxy9wGV8UQoJcVoCdfWm8Ezy0+xMr3x9UT0OyAdMNzmL38i9GuV3qQirE6mn6/e0EcpJdfrwmutti/RLdXyHXHhf0sjR9R1Jbwb8LWOug/d5mS0WikIlTTZSD1W4OYqE/rbTwA0DXP3ommFr2f3p3ulY5+GkHtWquMlBPHrCGvh+0xk8OveK424qhp6qKACN37kA/Xy9TViMTxKZ45E9CqqndR+As12G9vWR1lUcSt+JrjjGIpXwgb1nezUxefwh5LSZ5c+GuFCFPy2YQpPvTV5Ia04zMQ/9geHd5cI+981HjqHdEKNAp3miYjuJMyoR2sCKQsAYhWQ0j76AVBJH3hFmTivcCY3joZPn4XDpxLfcbU6cQn4X1wB3gL1itjv+yzHPbZYgGQFYV7yMDOD9ReS3mzAgAdi4ZM416MAhmTnqEfNh+giXWX6Ix7WWw+U+rHttuXlnm32kD5DUjP0QtytWNtL3Zyn8Jn8Sx6mmohcqhEWv9nRsHjRjcDMjPz73cEWCYDNWG/3nes3KkhKQrFkSvWUzOOFwFbFT0sj6YOIXUAXwTGQxJ30VfCLIREbieMFe6hMzOJTQnlxMuOFkcrvBD4DA/6mxRgDSv+3qnFxw1BGud6xiLymsY282hDpEpy3/tjQr8Pn0hqOUBzM4xmetNFEVFb+kfogfefeWs4cJ90lmlfKfE4xw+LMpyoToBmoOviGs0hIa9+mvo1qbNskTGmYqLhzw3NS1VqdBUYnAplXJYhkT2C3F3lYzhD1LteHF3CH7IO8+oiAW2tV90GMO7GOMnHAn7NuVsdhKQtkHiCsAOePYj2/Wpb4OAVTZ5A5In0y0K/7RvbL84ScWvoOwAPzr8ZT5MZVxBbCnb/IKYNovNmc1Z9vHoHzoVncTm2v0Q1++8K6jajFmaRKZJ9gwcaNGicBDJaR1y1jovsGVsLl+Gq4x5WaIm9jUnbKP+gprlT/mAl+B89tt/RVkf4QseYmxiMaY097RBac5uHFs3QNo8xU0txpfzQo8EegbO9fQe23E0UOJHvYh/rWcds9FKeplmI/8QNM0zue7qGZk1yr8rpLT4C5Sx9aq1eAXbGFnPDxOlpQai+aPgYh4Gf50n/IQrideTrxZNBnfSZMsPuGuI4Kh1zYNRlSG78CIyPgnCPQJ8sjyPiMbA1vN8HyscztAmWXV+7V6Gszgg4ykUpII6dNF4ZYXTAMdRa6zKbVCHOvtRnt56XQxSmbM+38PviACQoWqHqsqU85aRrtWTHH1uQD/JplbzVY5ClGyhW9RLPKkkK/CodC9gvZ2zR5MHv2kBWn5xcolQgwZxiP82k3SCFlR0uOEyFF/+ENjkMU5OMzn/5BY/BCv9JQ4owvTvOOQDm39Z7G+OpK5cqmF1Rus0jiXTyNYy0weiV86d0nv0rq9sxsF594m8NdjYljRr5i1DNMvt/flHBdJMRmjbeVZ3uk9jS9ZmWK17X7r1iAjuS8LM7yMvi+5i5JKzyJivFHXbhTbPK9HVXWU4mjmFRbc/OjMVafIwv+SIqQr/EW0znavhZ9c49cb5Fds/qBWnELJ5TRfVm1Lsc6YvKGG+haWdrI326b+XzSbCY+8QNEdHuLT+VQv8SFibPIuInFPrDboPgGPcbDc9ancPO5q/oqf5cmYPHoR2fSUsm70rUW3jb5We4c0W8PhkxOWyuUTr8WRIEETIA5jmVs3Qnmi4f8wgfWro/dErNAbKMzUzXbciRxHtaZ9TBmlkei2B93JDvbseyrAlEtW2vMLNai/WBG3gXftlfXJ9vnUzOeHpQTzrGH4M/b/3IchnCOLufIcdNEr/R3k6jMV5BF+Wd+SCXIMZqpIGzkp/BC3qMhXsSdQLlcCqm3q0tc22tyxkRH27yYgT6iMJum6hDTifmOO8B2ZKqODs6f3Za6NlF0pHmlg/q4Gj1lypWokdsIkOU5bvt1VwanULMkwSAI/mcZ9zZn/xehV3vrZCvOOvnINTAXLUjz9itGXzgubQQv1ptjHus+8Z9nOkKPSQ1xjyRV8tFg01a/UVHTLY94HWm54+IWQIe8MPzniYnlK9UcYrtOpWsB6PeWWUbtzMTvyIBJRajPFc38jMITCyrnMwsFwfNyNRhIBjbHV+V6DyOcBNLr2Yd2CKxLYhT5HG1HfFjrXeizjHXiZDEg3WJZ+dvNl5j+chLG/Et93GuvOmIXRXRVQc0w6xPfICSFc3yhD4l7Y445BsjQKmURNW2CTBo0U12Bl6Q1NufGeToTgTZILxxFYTUSuJI4EPR1FK2eK8f4SIO2eMHIIZY5yyWpXuSDEDWkpJAyL3LxtI7OUe4a3Am0C6YSPHnA/t7f2YNmCoMKTe5fHNtbbQgRp/1/QcwsLz6K+6aYzsaUf4+ijDso8+e+rXFDaMLACMEH3xptYi1+BHk7dRnosOQu6XTbRYOPBjaCs3NdQz3r3MTBcnXjsY3rkfyUe+IpDmU1wjN0pJtjdovDa1KM9eF6mSVieoVWx7d/7htE4GOuc4omTzMNRrZYgt0i1lsJNP/UY5TFS7NccKBRlxYEidpEOiMsGHC9OCAIzErR7TooVuj7ucJwQtdKt6JGtz5bVggA+1DtabABeAgh7yDKmpdTju3KSQt8CZeO9AGJdJ6U+kbNtxZT8nyewDPq+W9iFUXBM9W3RrWONEuwtCeXooZN+rPAljl/DudQMEEQDZMGRQC3Beclb0cFsXr7WBMjuCgKKMumF5louMqs7WwYJ/HKYNlqv9opI4C2z8mgJBjtCPrhnHw8GmdomsEts9PE/HIleXm/CpsaJGaSSHeJHNipaVYLOn6kFS6WJBnklGFo+35DUssqDNVDhCuQSz7ZaRWg2SZAfqGhC8eXufp1ajeY/eQyTRBlVErkWrbu3XcKtssyRshTIwxUprRNatMb3ITlRz3D/L1iQqsFygySd2dJXn+N2mxeUzZ6cDYPNqNB+QuSSMGvghW9yR7B4hvqhJzw07P+Y7YQA+ktmpH6vl1tQnHLTYDU8ka+DKydAcnhgOLYkbDW4Idwr87uahdh5pxxHfLNIGL8MBC1M7tw72SWwVQaN1ZAfqpKXNG+DbRIMAcRD7rQqREZgJlvta51Z+5KO/Ft5opOVbQXp2zqKBZYXdyorWor/JaAn9Pcb6uLin0cttr3N5HQod9Fa10DF1vC/tTZR+N7N2KaKvHii34+vaHkkbTcb+ELFqHbKBies0rqEMWSN2La9HtnFq+Hwy5J+2T71ixRJHvfI85fPS8cnwDjGjEuh7KOH77nAPRq1VYEwR6FlYhJSJOo1xVEeLAvttK3ONSyRAl5jCsMZkVr/50blks0Qp9AJbet29jkEZj4M4BNtf4ocd0BL2ehwe3I71fqEXtcakNoKlVodAeiTrmmRnd3EfmBjQx7Has0cCbRh/LA9xW+QcEAI0w9QVF2+4k5J6iegTiabdkNDzza7Mu/TedDubmMtv9ksf6rm57qrlaaaCfuREqOFB9qov2OGAkDcVqxxq+qw/kQzY4L5bFAaTYlUe3KAvJO6lXZzPP9a6wP5ZvA8zuYkWPKuN4tyQXEqy95nrSGd4Yt953DBDHoTpf7CPVvFKlimNgvnHWhOOLLQ8NEthU6I92vNI7en8V9BzY9h9pm4yUHJLsblb0hQGoSby3ZOXpNlF7GRjWLHn7Br6LEA21nyIGJM3GQAxt0eoUxaxSoPJ5hxHR1XhBb8B0bMbBy3s/ySr0S/Tmpi7mevc82jAKWAXcBKZK2Fvp28bhAY9FeqwpckUzDcxHHHqO7q6o94RXyZDy0cNGCvfUrLssy/miuo0dmzxThqrji2G+AUwLILSpwNwkV+K/hvMcSkJpCQKm1Nhzk9vuTe3rfjKshSVkSgIGDX0CuO8tsZ9p7wy2jBYbYLn4uagHnsQTwu5v/eK/D+tbRND5wFGuzyv0cBv8bBllVX6Hb9tXMJeqEvUGPeWXacULIyneL+T9KonqB3qYKotB7mOU716wgth/dAcDFVpJeXUH9OnxBAmtFNkEg3xuwhsVunJc9Nk+tTWubb4Oj/4iIbs1V8W2oxqPYb7i+QghMfJhak+hBCgJGVh8Xjh1m/X+8YBSWmUKAhDAv9h6/rJBYOy6vWfSjzCEMgb8JRn7Zo3OtBNrXLFoIJDadQ4yDzNqR/HfqP1S5UVoX9olm2FeJpKZkRXcraEjDJYIqKTxfiRpQVqo1L9SWFGQzv6Rw/UwVmETmKQZ1L69QEyx1SkfbOBwxuqFeY6pWhbJ5EOktBTf7a4gdTpK0O5f6mqLDQAi+ddkXUzPUnx2vNUzBXh9gJzOjb4T9XxIzTyt1VpHGUxCJalnyQWKwGWd876bOG+1ofo8+ym/peXqxrQgIPcDYAx1JbWyKsIFZ6DLfFy8BKabA6+RAX9OOrQe6C+Z3OJqnDPAD0q78EMXytCoDR76/zDZFyGzlvFrZ0Ooz4Jm/NF/rSbH1xH+AK9WLH8ToTeX4r9vpEhw/mcYrc831F+3mhTnUESVM5hQklZGVtC6OSNyXiMeGEy7lLhO//9Hi9N5PRwsD2hAx/QbgiYg4hT/cDWE6ltyqACQhp7eG1IoRlvJY0uEuzc2zA8S5o/U9Hae6+Fn5p34llxeh7IhiFaibj5/+SlGIqD7Ps9npqraxJB+kOC4eQh9DYASf1RPJLTd7jsdk0+QveZIYaz3SF/UGmECGd5pzVab+pwNNvtLg9wA9q3gc6yInqn+MSgKDLyBU7bePG8uId+wC3Alh7yUVYb5IerU3OVRoEfM8mQP6PFQUJK7XKjxfqgW+YaVtbgRSRUD8hpbjoUT5Saay880KR68H51Yz/xp46hUNPQL3DZ3E/xlnBjTf831wB50ceOfr7tA78MY/zgCaRY9j+O943RnuqImMzy2nfs1+BCJmtKmi+DUXa5JqdZn4MwNJ3G9eFXuaJKNJliOZo9GOWFREhJwCWsiG286l8NGOeRrkab2M8zAlDO8gG0KIMga5B9aZk/FzQhj/xQjGBlxjgLu9gv1XN1cZqjfbO10CQI3BChehzPqcfqqq4Fh277WHd0tPp7p0AWegUy54rR9l05h38pgkcIWjKS2JqQdmPeaXIYa6KOYhHZNADraaQUGtuP1MeAKlSFrUdxetqiclAwMGWFoY6RTmdqPcxb7wU62/XbmcC7rKFs5ozhEWJyXbaPYZlxrEelXF3QZHRR42qY+5yp/ZmnfviLsa2qBF+CERl6w2MwN1CRGJbS9/DFgm8ubgRhrNf0oLi0SfMPElKDk7n9JzIgTEDAInqla8CE7xibhI8XIGwzlnrmucUSHT3SujKY9Kbx/mhhC/Dl1rI6YNHC704ltL0/UQ+q19rFEwLA/Im7gcPtYXdxz6SaHAmYfiXm1il1qHq3hX2LB2bXrWIzFpE2d7U9T/PfTKzy1LS2G+xNAH8s++XTUbQ/ZVotBbnKu+S434IRq27aHhgbXw96dFGb78SvTbA8d+BNqJAC0O0E3TFBIz24y1LzWsOyoMzs3oNyUoH6jh6GPWOCj7nG8iywuCyAe8mhsg3HqVAER4K0Qv7bgTIrdKWVdhmacJg6ZFbD5JFHhX87QRUj9NpTLUvo1kAWkBR+C5gLnJLh4DAZgVedLCpiUFm/IR2zFqCjX66D2VBMFKi1Rfy/227UTvvPZDvT6FDRRC5Ah69DUriwHu25XkG+65qPK5wRc1yET0uR1up5qUNGRlBxmsBGLUUCmZGgU3YQGSNEp02oahf13/Gyzax5nBW9aq0C2PHWP9vLbpHOf4B5+fNJsDXv7si5wDrGtuqpDEI2Pnpm8K3NeLqhJIHsMdHSNXzPEw1HUnHVAqd5xehEbF51hDbazpGYz5obF5BEKLCsG4Od7s/Wfmrq2MOLy/jXyQqKXZOm4qUs0QLwJkS/rmch8JuTAvCvVNk1ojwMCnnsdqMp/32RWBkf6RAAh2acEPcOuPrDYf6fOyMovsHLpS2tXz35JIK/NXMfxEol2A+yjtDNUjth28JRhA+PfRmRQRtrofWl8Llxf1ZuL9WLBB5A5idZa0v6tXsdQuBNvpJQb/BFkGPhmjEHEB8IH+s4axZg9aKu5azy9JRl5qwe4607siWYlGR/OwQhs+GWnTVaCcYaytszcoIcvKiFA25sVK8c3wSKg/BwpG6mT/CZHwxT9CLsij1u2ClA4/jbCTXJZ0nCXakys6nHFMmbFb7A2pVdpZPUe28QX3WMjYuNPS4QZ/5ljX12uHDYZqRb+iABz7sVgDxi7AX1I7mQn57Zh/iygukmXJF/gCN4ucAkTUkaGKdgrrvjcnhBtv7LSHBPTXrMej+YmKovyo8ccoiZqtrAhbIHJ3g8Mll4abUau0oBEvjkst36eV/QkXQJmtLJl0OxYctIeLKNZOHaTJHtZ/2RvaN7SIA2qjeQAocSp9Swmpm7GTCDdj35A29LfJw9+PGp7fLL7/DfDmnQQunlmJ/6XFwKQRVGe3Xs0zMh1FO4BlXTsYKUBDRtpLalMDXDsHs07HtvoNIonR/p3gf8+Ijw4LwylBFY119bCnCmJmTNingzUsSeYyxp1DumzHvTgL5+r8TFO7CBDEwFTRoLFcFPzTJh5FrLKC88naGkW0CeCOdbhQBk0vvLJciFbBxU9ChsrGXtNWqhSM4lBruSudMBXDkW6MNHSL2dz3Kl9u4jph+L20SXC1Xq0gstRP1hVI0TwzKLTIxBVIsou6jDqfWlVkCiHwxqJQY8TyNTlNLAHKETF2Km5ZRWDZwNIdHGtwxJamUqHIJiCMo8Uu1NX88t6IIv+qOvt1UPRpbQIQfuGOx5QIWKI2tx7RGTUXv56X797Uxuectms1BsT0Q3nHbv7cK6S0a2SzwP37q+QKx8+TkbQxGukIraNWOtj8362J+NxTNjE/cU09mtZxA53B8TsoSEjQ63/w7/+tQ0XuexyNsoMzHla1q7es1csQ8r28dY56ymrNvFtRlsnNtGwF+56lLXANdSLtX7HzhtADS+w7aidw2jnWHOv+KVlcSjtCufvrI4+KCWcdpCazZsuLLIMVFuYUQ6h2mcyvxKCjZqOqsGpYtmW5QPxyuVTjL5f1TUeHPwhggf8WgTRg1jy5jLvL8CAQlV3tnuNz7peTT4LI1Tj0kM0fHIcSsDbnP0E7pUTCNke/qairxYpTk2CRF3znyViJmvgDI8DhhX0pNEdidw+MdzzgYrMZItBRPrheIlsdg1/aSR3wQOoBANIKjqUQ7rToVA2hdb1O9YdTKyzYp3fz0xd3YLBY+sptZOdC/iDsKu6io/MV/QeR43eO5bYD9Zs8U7v+Mbq+7gWnJZjTSSUUKA92N/0qeG24eVplSrAKlhc7qDmAVry0eneGgMMrAs/46/RkN3rf0MJjtsrYc3nU/BreMV6Y6UcR4ZOb1G4VRVJq4qUMCiUHQq4ntGkJEXv7NBDebWNZz5DrqiJRGHN3VJQfFOXMXYRt0J75PheePoGb+mAqc77jN4q4CKlNc7sTEMVD3zxhhjfbxB8ZUS1veX4XzUk0bplyawAvmAciSjrEPrg3IpiS61W6XfLGy8/wL958+5cQA4Jriic9vpr/aXSy9wXYcutXMnxbx16R4Q1ePQQ812HfPNrr8tiBX4RiAWWFE86JmQ7Ah2DP+HH+p6ommhzTZL7A2b5TwpI8vAbnA8oGBjUX7AIdpVpxHNtlvxs7q7sOLnj4ar0avnYrsYcAXhPR6700jF+HkD5OfTc+zzF6uC7pfzyZhHRZtYSy1rNY91NvtwVufGTl1+g3W64JLC6H5fMFUSPmMcW0J1g5PmdUS3844h5pobYM2Fh1A+c247toek8SPuhxbilZGSoKmGQHTgtNSQBVYUgl8+GET1p8Fz+3XPX7jsKo60DPlSzzmgGM3vpt6d9PeqTlZKk7EnLuHJZdDCfLiGYQKNejC+1BzLvRGEb1s0ptgguvim+LI9jTgsGHZknaKF2hg7Uh0gOIg8Gg+Ion+xZaTvtVETATWXRp2fhlyxm2c1DfpwmVIuROB9yIO0Z8m1Up2OypZ4pb/p8n6/yY/CO3lnT1aM7HchJFcchtWgx2bSJ6BdnHIllD0ZilQkhA4fkKIwcXZVwLKFwaf3aNtUUgqBulHNa69ak/tXhTIJWK7R+5p3Om08BumglXgdNaFCmCso51yWK/bhVTwEyBgoVYU3tMwe2Ttv9f1ljVp4BGouSfySGoXkL+JpvcstOOY4R6zcdjx/F765BTEhr+kwJURxZC3uND3hC3SfPxnSPymggmdphgvt+54smh2CtAhH6SdPwNYwwwyBeVWZj7JwAAewA8o6w8zXWtMoAEiC5uhVEIJex6f3MtyQbZhtL0BifSIbnL/hJ0KIEr0J3sb8FGPs8a6tYTEW7ZP7syHmZnKU31zon4DS3qspt8u5Bad0m7W77qvP5gzSIFgelhV1TwKhXB/vJxgedyzYvT8p+rIyLEJ5lmEM9O38SIga/w9Ld7W2u78axwkoKdH634CzmgplvldBegF5vkxSgtMtCPOGhuapzq7/plx6U3xmk/A3xQ0ZLxYCxFBlmLCUc6ivWjcnQD9K9yCUi4QzvYaRNcSG4sLVEbwvbsxg9WsrUGCxAU8RuNWv845lgj7iSbt22iZ3oOcI+6zkTofuM9GssNFZbUqt5G0a0i186LSpHsmmGzEPHLfyZSQYJR/LLhVLa/rrrZ2LO5Vm3Ox73016pwUn1BSoQCyEHzMx92syTZCJbQ/7+07k8zfVcStQMCOsRfIpxPw+rVB3syDKD6KaIm/ynZm5/Y0glqNXF6bd1NZc5wtWZbb3eDcDqs5UTaW1XxYviASNm3HY9zq6DadUiZzE/SSYwk7III6+mwCml5UZVJqTznSLcOI2Vn3/CI/IhNarBFX7rF6pJVIwoOWPGQ+ehqttPozoLZOzLj1TNiMzAacdVaLQGwMruxIgKYA8M0fXruEz0PThIXMrYFUBhZqS8U1Wt+bHHYhzE/h8hErvyXX+Ue8H/Sc5XGI34wtf4Ioyc5CDFGAhKlfU311LzJQvnIiwKWJqZBeX3qgzjqZBYr3Ok7AvKdy1JID/vSV2X7jvdqk2W8t58kIlz6i6++WSlfNEtVEnxwX/oskF12yO71x5n2nr5eDimncElc0c+EVbKiwxviAZNSTuMyyhBkYv2gU2Qkp8mik3nK20m7w9dFINJKUPDXDDMHiq8NJ7SyFMo35hz/o6jOzwgTib2iZHmtqO6R/vopA1oF7UBcP9GswHJ3kihCRrgVuQpH4njGRf+73GDTlFAM61xpX8mFdnl+5AsOPKS/5fzONN3FzoX+vPkbYfiV+jeAU4w23obGNMRFYrM+sytvPu22LHzUDbMTeHWjhz/PJBIQe68EZ/GJsynW4mt7OOCDCtmrSpGm3kjav49mbxPpI7J9F3WkR0zVQxxksveJJ+C1Q+e1HeGns02hMqARhoxITuUzhbCg5C/DwauhnRAKWHCvgQD3XZaYcKOo8j7Pum/2BORiSZvYXHP6P0lH0KaYrqwAYzCCd4UFt6GTxKPmQq4LE9drNxwRNghbd+0LJW8tmXZV9ehd3G2u74dxUNQFR1SrBOKujKUcnYyen3hAs8v9A9myX/UKCb5eGEa+mYGvMhoJLO7fJ1uPvbTKJkN6B6FdT3KNxOiFeVuYlpWy+VC6n7O5SiPb0gp15u7EsEhZ6hlSCvTyltUagqGgdnH9H5IxM6BLyO48M84axW7bmJMmjTD/QRDIoaWCRMr0D92vOsnWNyWUMbHlbUAprIUXYHEgJWXGO0r0TGd0bF3tDEwWqHJcf988mGUEU/UOIQYWvWyRuzSC6Oxj+paotLDYHo27wsaglW3u1EUJW7oNNeQXjWIhrz/CeGlxk1CSzCoKkEERJJjux5Nq4r6lynUUTMFcbakaP4G6e9GrBPO9E8vUhmvYtefXcjFa50UZOdtZ2KuhOBRoRP3PxaSDccpZhevHe0/dr7IPVhlnYXrtfgkafexo3SOX7jPZ+I5AfvhblbtjQXlW7L819RP3Rb5nBe7xoOJsO+5wii+ELa6B2XHcQ1srnfrQvn5quO3A6+P/uYQ0iE3JWqLoA4g5hNx92nVhIcn0iGn9UvgwQ97bxQVsed81NVpNnJru+YGchtNODWg+14gVwIY9yB7rFKCTCBz/QfWPZ1WnTKdFIfmMjCYE88ALjN7e9qiglI9qzsnMEoHZHjXC0wSK5hKoJ8cZdhxFcUwIvElKTICXrmtjcGZiEzGvTKv4vwpGnZ/VsNaCoBdWkvXQW7QpMv7azGUjqiyfyesg5dQZYHRL2vwkrLjv+HS1D8tC1ALWmM96scucr3QXtq2IZbroaLNrTFKOVvGy+ZWJQnPmJXTYnyvk1Vpxsr6K82+er+3ViFamJRZU8AxHiTkOR73NQB44xRxlUFugMEVovjkTxpS8q4Bsk7q+1wj1O0fMqevp23bOR8Rc88cbAfcmM84Oh5HJxcn5kmEr6YWy2/bBiqj0ECUlGXIzGIM7YFE+fn4T/0VLMZKDy4+yCoiffxLtjpEWH7wgXALrFoKAuZ991au5t8aPIZeAzWyIseha8MdHdBZbV7BrDl6a3d/bF0GjuqpnhN2GD7M+S/3r62rpUHnbPedKo8ROiP0uXtE8PqJX5t4WRH4hCvG+Or+Czlwz2l3/2SB07T5vx6UDi/y9Y3lEdgBkb4tHuFXYHApc2PbquyvFYmupuv7z4aJKd5xZjqw/EOYm2433b98LvkB/s4xgrghKkmajUzmviTZ+m/O6iJpr+GyVxgWrYd0viDt/ZW8j/MZ8YR33eNvehQ+qF64Zlbx3TrDOrPobmDl7dQoIeTa0CAv77HecrpPX4vlxEc6V23HahZvL4L8faIardZBAOtiEqSCaGZ7Mkll/jvl6e5HAmdLBr2lHfSjVwivsdpnvVpUof0j500nGWr0xyADKPdLsBdktO96vxvmbyaNOVSut+sOPJIRctJLKAZUMmvbSYd9Rf6lp+ZdUKgb5GV0Tb0yFoKQzNfVULgZlxtzoLMTKZPdi/FZ6U5KZaibrHTg5B/rXx314b4mbp1Xr63r0MHQC2CJfH4rou4obYlIM9VWnFt/zwqwegqTtawDmYS+SuYVSqAWoViFAEbUfBkxc2M1xBkeraj9l4r5bYchqQ5IMLmBHeEiZz8Sv3K1Iy+L2VQSERUIT1k6edBesbyfYJYiJyjQ1XNFx+RSrJrGURFTu4qOYgnnkYd6EDnDRmrJ8MlOb2poFpR0DpInnGBfjD0jsBsRtVRhNRSRYd72uJkNp5xYHE1L8p3eG/c+iE3QRb6ZGpp3IRM7pKbMusNes8xSMEh8sSiDWJ6p2UwkHTdxGvbFgqzrg6Kk82hvcqKi1XZzmLSdB0t1wxjqW9MeEevlBxaVSZWDBNwQ9m3uGhF5fxsrlWCW0Ch9kgkGfPGffkRYfd0I3yHNsiK3mNPcfTKt6aurUM8wnVk2mJ9oAt+CEYPuKsS4hoHZwHWW51ssYyYk1eI3r/RewSyA89wAWseF/bWeJzsgmgS5RF41CiktgO36Aq5DXr+hWaMWAVn4CRreqPKSLD67XqdmBAh5hUoJ+b5hielnNhiF/+M29xnZvf388vuXWQ3aC4mjhJ0BAWYjmKtapynF4ndvJBOwc7HtCJfMI/wgqYuFXSGJts12N13kfDiX8uh1+OOYbuwiGaiBjTzHqAa8SAvuPhsD6+MnNe5lP5r4FTXQE+fRyD0YjxiP/XjQfekDN3ikLx2A4rqODJ0AGX8CwK8raFenbH3OdYBPQGpiCFRwVDSLAN9EL8Ndxm1KBc/OeocyNoj8K9wNeipukthIhHVUNPasXFMNB2AwKBMwefN5tE9lTl4c5W2gvqI1p3oRnvNvT3B9ibhbL8NQbI8oxqU2lNUfAHaDw94n07rkPiElfUj6W7kla+3jWvpMCvzPAOjWuvdlrgDr89Jq9wsPxZxP82F3L7PxxuIbRm18NqfQw53pIMG9iqoNSrxo39Hv2NhdyYgZpMC3NhZBSK2EhOle/pB9nozBKhiO9juj/y58uQVoAbfIhuQzmHxnc2+XsgeLcpSuZSP5PKmID+noYv/6YWOxB6xXm93APVat+Fn4PAhobfI2KotSRWffIkIerptzWqk3hSD1K1QLonjN02kYRTfbP68SL6mozmVQg3ct5MqJPPi6GGgydgp+KW8SAfOXjmVufOoifTHrUHqzyGNXJc1s43luSsgP6XEcVd3gRZrausMmdWCIOHihc6f+85YS53xhxEble411b6attE8XrZF6/tHRmGTWayW2xEfLVur/bzF+M3HHj2Li+6gdBmr6u6kEJqbv0YdlSXcf3ssBmdHPcDGrWmOiNXnwdLjBB/Sf7tf992l4vOdxLpk+amegHLPYouqd2ls3MiwsI4Pm7PQRfBXC7F5YjqMMkf2KzSwq6t8e2tRx7wFf5AaJ2yMNbzd9fIJOjlPdhx9TB5AfoOMdynA7mxP2xoX9+7dGkcJXvYI1KFDkHms2IMBPYXpdK8kFIp4h5JCCeK8dgTcP8OIHTFzMDsty0qBdpQqAs28irnN9TLwlVoWPIVpYP7xgfyJ12KDngsZah7fvmQhhefASfuRvg1MlvmzYT2F3m6TQE0GkoJ56KsyV7gIm5u1tuZTWbLjvP6cmcH/lQ1G+lrydFzCiz0qPHH5WDW++69lbHX1z59sKE2aSdWm0WDpf5dMJyAtW2N7+aN3ArKn8yWHs+NVD2RTZ0WbSRhlBDzF5NXJYS0QOK4hrj2RSdXCjeap339s9+2wXUsPt3a6HQS9pE9AcYczknU3VYDpcXzWNRVmJiuIQiBLwhgMFVrUw6GNVrisbHSuB+Jov45x4f7h9Vadyk8yo7omkenDywKYxo5QvykTb0I9sfFhhHyS4hKVp+q8M8oIbiykxSZj25UnEjxQU+qpzCjXjxJXZKNzoSSCCrGOHjjuVHZdQE6t8n2l9ZEPeQAV2Bgn9ig9cPQQaxCGDCFdUnUcPEDiGfOE3TU/3P5RbuLdvBhCjjw43b9k7vTjFCoquOgCsl2RWZd3ad8t2bnJrFzcpu7M6klqv1M2vnWCmnaeNbRbF7MPGIz4YsjCoJdM0RSiT/ufG7RxHoMK0LHYQid4ZhV2/SAwrFXru1UvaVITQUo7zNcj6NCS94y30glN03Edot3qmgYZIRQiwS/Ep5Jqq8If9KfwGHpa9or6ENXbxXNTI/FsEcsuYW25Dy8UJY0eXjlSxk3l3ZMjMTjfiGRsXzdghx/yN0cUuOwCBUA9XSC0o3aBp40+aYhMjM0qK8fOWglDJrQGOSt4uB1/iuJNWWGr7CzX2HtK++yPiqD4Roji2va2LebxHTy1lKpQEgUHzYVqX6+WU4NHHq34KoIB2Ynlgicw/3tNF5ldmO/IxnsEv3PsO7Qng3fmW/9+SQltCjEyLOsrs/Rxk/ekPajDHg6Dsbd8VtetW/Z1SZrz1DbY07dpgUTOx03EmkNn7ENwN7QqH6F88QqDqUjnxblgYngAba039JyveZAwxJkNdeO/QimLPEeMCc3yyBBzdzS3grIMU4TFdZwY71BpTs8iVCojlbVsedXbvU+cDeDFS5cDdOX5hgfVmiI3W+eHDuhNqSpeESWjPYk9isyFihAHPxR8K/U1Kr6bbz7RXoSG7wK6WdYX0hGaHdy7/vYeKuzAfaKzs/U52NYy6v8lQ277wqmicth/8w69+c5VD8iw5/wtY4ESXl9PsfF1eQPcDIAyZoJdliCuvntqiI7IgbY65rdgbR4zTMcXpjVwu64NYsUn9X4+g7hDcTZmegGU90EIHYS1FCq320bhnUjnqBo7Wd4q/KtFOAQr69kE8LX0ZbLWGA5mx34E/Dq+iPujrfoLTTWH+QccTQ5D2oGDGCXp5DnckZQdoj/ZLSfIxmpQzSOxwgUedD7jDbFwKT44R7KtqTCLKUvXkHGa2wiNTr8x3HImGFa4Xh2D6q3M6n8yzmmvezO32z95qH3Mn7vEsfsCuMXNOpG18srew0VBstLIEWMUe+bC0F+RAVclkdzGoL6LnUVUNfpdmFoGgUz95OBV/JxO8fj4ySIwG38O52ktjLWdcbslSfuixCl+0VJWz/eyocYwOVzT+U5JNErMoevia8R2ijn8eLSgIB8mBypIEk6pSoLYldky11SJpTVgMbvs3rL5G0uqC1dKe2RxqcEnbn92xGKzTscLaidf3jYROlTsJ56/rUgVzeN6UWvG2JcAQM2PmT3a0ZIdHORYY0yFE56ItsiB30GjD//ibNnMvlDjVCKzeX6Ae3lZVWW2E/2xLU4fHxDklL+qsgJI/7uYVO35WffEkLfH4zlraqWpt7I2Bi2sRIzyFRDEKcqFiR849ck5EdZF31akH2WpbqF9/lvVuxPi8kcP6wOXH0uv8igQiqWb1yP8vPRVbMKMNV3AH6mu1On8vHnPAomxE8v30bcBGsOHcovt9s8IapxSYYBLgFYovEhY9JmCyHU4acrP4JW/URN4kIUclnNNM5KHa7I1NnJaS3B6P12My7Wz16KZypisqYhRA+E9WEGsphYJNk/Z4cdNNfaIUlV5TZP8mmMQN2etA+vHqMoY26HgLdN1O8FbcDa1umv/mtVYCjSEhx/yN42p6PCJVALLJ2iWrqqkFNw7CCmZVM/jVysCznwtYoX7Ca0G3ZqI7xbL77kgGX8IdRE8mfwOeK07Xhc6osd+oWa4meWzXI8jDOkaEKk01O6AU6vdOM2jJ1bwbF9EITAL+HUnk3uT5jT/FgV0V3bTVvcPEHr153JRL5fEhZlM5pN6e68s+L1EPoIqeTbjwd9UHRt+bE8AWaK0Uvr4HlTnQvNQw+9pcRMUo4LMxEtt9Rqncosae6VwVi9yFrOPmAeLtcm5D2Z7aUVqpzzPB3x2zBoouNPnelpWmwiQ2YSu0JfhH3GsJB6wF1ZjN8AHKEIPaABUQH0a/nPpOyBN+c83pCW7U2nhR2VJepgFPMoO+HwxdW7izwgCCD3I8oO6dDYnc3lEAYiQ0btRrUc5W1Sh/8oes+hkGe1pYKuR1ynjN62jk4WjCt5V0VIFD11jikzkmPH14cA1Fi1odzsUd1VPybHDjogbqBVXadEf6G3DSTYLCpkqpwwEpsLe9PzqDoFD7Ma/RsXDGo0BM/y/BHV/zA18HvV0QFxMNffu2TYwnK+oZ05J1XVsDlhOPqNWaT1Yw0NgUEATZuaYEqwfabwujKz5pbu4pHYnIUkJqaju5Api0cjlb96kiR7jHWwq/8XPSONklbJWz7xhYb565d4VbJSgvzzFVnCMFDC3JxUtEiKJMXr24fE0lX77wNoS9FqJebSXjE+3lD7m2RXoHvfUix1cQOjvKXks4YJJG6oaVGPKS/Gm4kaBgEf31Udi7VLobolIQU0Bf1EmnMAeehqOSGsKZDGz3CYNfLkp/+RFen51tUDmwIP1EJ3u5Mw2rG0eFFK42rBdhl5T8fz7gTgaHHcdkkopzWgDE2zfnlCqKh0WYVmEptUrbU4if2Jz+uzyfsmTBmUAL9mzkmZ8EFKKJ83xSnfpDEno9xgExQI5n5Z1FSPPi4w+TrYzU3SsYDmPAiUUcGw/2MxrdpoQStQwg8/9S4wZpl+G4P78rlUlHI4aPUlKaJbN3PPUJusnEjUgw8VQOvnmAb7yqixxxy9zGvlAZh7LAe3SDurvvxIJI8jneNTXb1cKiiMqpO4nzlrCirGhfOzLP4Gt3SGAqJ86/yupUaNHwTEHlthsqFgOtgh/rn6JbrKVT4gCv1C1QybLd8ZMR4H4xEmnftWpCaI9WJ/pmS8Q9ztVBHP8f0vKQP1MrDujZ9+NWfHHCFFwcMOhwekhK/o0XvcfY7rECA9MnqNnAZeZXqlIcJ1Bh6jnam/VV5ajtdZ9Znt2KQh3ASWzQMlT2CnL4kEvw1TnMZEdWOd5MviGaYJnkHoO/YPbo1Jvt6PcxHL/EQ6YRuzxKIxrrHYR6Rfbs2E8JNYOWlxjtHm+ZFkVaJ0M5WUFrZkwLZei6a19IwufExHj3pfZ7+8BZDGQx7RcYAZtc04PC5lnYp8sKnAVOdywldGBnBXxuyRVMwd+Ytmw4+TQRXGUCvWAkZL9aOJvxV+uFLDSwk/9ztM/BaLgB16wpvEhLTUL+KBBNtG705z5DHNTderrZhfEhfFV9gczGPan1A1NBkYARNonjgjSGrdcogupHd83ra+MU+vcuY6FctKILmrwjT1D31yML64YpMIr+PHFIBxHV9s72STKjpX4cADi+aWF4/lzTfao5CDEhHiIvylnSJ1lsyJKc4InIWi8qvt7+a2FEkj3B78IfWyK6xckAn84ZotmRe/XnKiksa5LwjFLoNNiXYsmKRSOiGQfb86IAIkYrdrfzBNh1R9bFsW/Y2Lfefb8gOZsoNyVlYgMk+YHlnmG0nqWEE+Da3FzoPCowVNqzEDzXN0c3rosZR+1cuaRwjJAANIvj8ONpQkRJJac0EmLwKthf0GlqHevw6JAweVHbHL2FRWaqS4F0Jd7BqCMxfLiztbz2nwHtSrJmLr36QCzaoeCWGGBUsRtHkIVEt4XAaZ4YG3WjO+0OT3KtTDGOh3aq5FCjgHPezJNkfL00Db7ykcW2qtvXI6TY6U8/XZpucvpIaiE7OS7LcGOHsIpA7a+5lyLl+kUKOGw0cM6C+QUcVsNh/2cyGkkB96DmGMdaiBU5KJBidAGOtDofGomx91JvIs2N7AAvMvSkLUCLJlot6rIrOh/5cGZQsUFZ9cx2bBfol05wlYwdPZ9wPDGSrYxCcDQ1WKAHNgn+bPv+Q/qinTx8VYq0jLUDyI6xsRoRNoD7hKu6Ogp3JFHwXl5MMKJbUZpWyaXvtI6P6VqXNDr/flmRUqtgKrQ5JrKYb8vc5MBCexv3MVb9rvYuto4l1N9eaYTLlopfyzaQ/qHlrzYeqSFcCTDcmeJArzomLkJxay2JwKnyCK6xKMFa9onTgqz4XljwNUiMwaTCehpho0ZuHTAseo5DWNWl9FMt5UL38I4PRLsX5QG9lYZxmVvevTdhk0/icNNUSYgjMLDUm0Ze4eWSU45CzZl05d2fUv0EVxyIWdmOb1BiPQgC4FZ7g4pT8JNAsTtpNvxYsCtnx7DZ0s1DKohYc79SlQu6GtYtiIez6VPD9y0YZ8SOxfkgsSADic8g45E8Om37rIHnz/uy1hkZDDmYG04HsLeSrgRkgXPFDxGYfv0Z2mmXrmBqTVBrU23f35KmJgw/pTvqALssdKYV5NI3ik37VdT64lIilmqRl31evQZF8uEYff+FltIDOhQE9Lli41JmFiCXKlOGqhdwZzc5zBUChbhiasuHakhqNK6d3d76pMpgvy0ss+kS/VkWOmR6T8hFEEGecWiZQ4NtrwH/lYyrL7ZD0b53J07zVH6aNMPqrrV/C9FfQJUbmm/uMVpAsWZ7LI4T8srR3x0nrmhfjsbZVOxUVq5yg/7bMM/mArvKpLQZ1veJuJTAlsIR2g2sXn4WPTgjxrgxxCsQixlEsRCbFuFh0KXtWOqt0qpgxpu7M3utIlHy/SdrIYLG8tkIrxhPouqIekGSqfrV4uvL2CuPWA1NdzLSI7HvB1mGULWpM8tNv8qVjl53ScVqYPhy8xDrNTDGBvYzW0SYCGjxbS8SOyEhZGoKAsfx8Gk+xgkT7ygjjO5gbGbBqkN4Z2ojQG41rJO1KEQR/HQ4BozaXxMk2aUwSfx8rwoukH11QYQbYiuqA+kCSL02Wn6a6Rmk76OoB4kxTYpdeeRFzFyQUX6WVGSaTJzwrwOGCNM+KmRx/7fn3gk8m2kExHWWhUc9j3qbVuYNMyNXohB/6w2lsNhquZUugB2el1NDCOZZUvxAYWK27u5pp4CX2T3SsPsRS9PHvr9BlLnrAOfdaKuuQCs5n9tRymqeWxEWJ4qEuH5TtW6AzH1cleD0kvlCSjy289Zqz/LU39gAgBeQOFDfEaCEKFlYU00c6B261pCqbGzfKVqgbkwx4MB3W1CKoj2NVM7yKKK8YlShnWjRUcCEjBMgasFytrMeXQoHCiKZeAiHmUeQSKAl4xraMEFigDCLDDfEcgiPeQirYXxV0mYpLPttCVTA3Nf7qIDaNcGTwcEXFUHYY5uDOzO3YrdBodWKNV9C9ldKVuD6Ao5Cl82p4+lqFjNzOobJjRCsyHvxQAz2ah506E0JnswCpRExLrDxSZ+i1DCOSNPcEFxr6jjBrOB+Cd/Mco1N3pSvk3AMoFDaqbdjmyf+RakUJGSa7G8JfUb+G20ewM8F/3rfXdDlbB30QeGsHgs1V5giCr9DJgF9bKKa39fbZLCv0f+6sceRVLnFDkplNpMs/0RNYwf+K19KIY5UlyfArxHLAJZNsYfoen0TOo0yhrBKnV3n0n7tfabpjzyfqEFX9/lS2bn7BfcwpG2fz9mhhy9bcSMNoxa1wRbTvWvsBXdck6v9TmcoMcN0edf1KvEnPyr+yyznPNxzn+IjamxCQPfbzh19bdj/ETzghost/2KGxaUM1HE9e8eG8MbDhzf0k8nX90lmriBiIZcmTDoF8UMHslGxhGmS/SXOfa/droUAkp1G0VkTnOd7k2oeYlkPZCnrYbs5Q/dqdjEpQKJxhQfK19xAC1xTIuOkQeG4hbxKgR6jbHNM+2c65IwL3S0bZ1n+EZKqDdnfBUUP8Wt1GXw43bcEjaIBVkzKnG2xMHoqokn47U8SlcazX4OiKO7UBtpuHKF/SUH0bFGKY7Ikw/V4+k/GGtmSsjKVtzLZQqMufD515PruZGLxNFlLfv9EDyf0fjcGoaeHD54FoZvjlRK7Wo+uHRzSvpZ0xpISj0o2Xv5hkfID8A0ugpaRssYtf35DLS2jKwrC4LJcTTlkC7XHqZV93YSakvQrMknybfFOet6O0Bp4pQ3znIzCsA3rNmSg+OZ39OvIkLvfHkvct4C6Mg1LBlrcGXi9Cv3FObi2cQqbfn4VxObesjim/Nw7Zn4wXf5pbdphDRTYxgTLxwlywS+S+mT6ZDcY9Q/+Ej/Mh0nd/5m1UD0dkq+5WeHn5rCzcFKGc5FG3sCw8pt8I6i5jOaq+CT8d/6T0ufTl/IXAREJyn7uN4F0FWxi95mr3ljNQ5aAMh4FhLRkcVbRy8MPE3ozCEglWtpysGq+1rLXhZJnnJngu+x3PsdXyX5ArdzIfLwmXFjbypVZ1mai2HxSdWxOdrqDK9Q8hqbVru7wwoiLdYke7oLqi4TyxMD23Q1on+Nve+Rl1rdGRyvQ0J2DpWJ4E8RncabZDLiKEnjGBLSZLLxldR8fZQ6qklI/ItjdC4MYTUbUroeXhS7VknbnaQtJLlXlVwvuxghsXGrG02n2/FqvWV0vKYdITbkB7J07VPvE4liWkxZf1vqnshi1JWHhFqXKvNS/r+VTOwknu9hHdUC6aMbkAsoP9gFYouib0L45bDF0ZgZ8f4ikYXXmPq6APOmQhe/xNzi1bbkq8Kz/LqsHRzbhKgu39X9PSJrDOM0gxBGqELUTBHFAhzoT8Fy2xDNWjggLF6wEoU02EvRB/1lmp67r/ZGl6zdSnYPqFrfjCj1mtWVADhZt2J6zwJwGubpUDsXVTjfMhhmaRirpWRny19ZjHTq5iTDkeZkHHtje0QZyeehXQw3CQnYQxtKjtWDAWrkLGUgafsYR2z2wt1rUu1k2SdqV56Nl6Xn2+WHlW92txkhhIMmOaJ8Xmy/iDN5il4CS6wqZ7W+4h3a+dU3VlbTCq9ylaHuB6ocbjIS2VrXoaBldErPws8zyuGI86dJ6r6LJPdLSgqAIOj0z47uEdcM4h50EdNGUxTOIJGp1jfRxk3ONFCQS/N0e4UiLODT9iB646qvl1ZR1t3YEgdFWkEXWDO4qjyXqJsdjKL4AzDvmRc9U2rjS3TO2ZAFUeRXAoQn7MXjRRw8ia/dAGUZ2nYs9vLHaqp/OETGTycUksGQFKIHYX8VfWuDBQsdlJs8igBqL7nZ9VRVukV6Qhi9k4D6bRCeXW2eCuIVoJhwghjbFGlIDAC9zJ0MGGlDIk163xTEcBPJtxYUh1mDSqtuE5isFseplyimJnW2D+23PUnuNbsn7DhuKQsvExEAFQ3RYKHtdHP1Es1WeQxzxX5Q5syha5A1NB0Q5uKSdMg/2hEKbQHXSMCNjXB9YFdW/xL9cNKHjCQOBninbgKuJ159Z2BTYT1ywvL0SSNk5xAkAvBgOAK0VUzErVa13CFoSn4QmOL/MtuboowPF8FTMtvESAZGwP0Wb/VNOYLAog463LZ8mu/ZhbLva42FcTk5plu3SjBqeUNwkCcCR29mphqb96mvYrQGs1sINy1MP4V3mrzpgsrIerx0hzIIM6UDNvRt/gJZqaIEGtAO/1DKtcaLHaUQ/gnwgm9f+hI5kfMH59NbLQSwkWbJjdxBLpKz7QEGTOvYks8FykWoGhixvOfW941hEpKV4QzgXFzyak8EZsFteX4bPAkokJXb9mDvj3+KOaDEOatSfySn2CMeWMaKWSEaWNVoLVBKbSOR99PSEKwyA5KXTNfIQra4Sj5NBt8ERTTfXU12wD9Z6P8Iek9izRlZRGRqAFQAcTfuznXK49XrotWcP5uj28+n5alLjac2pe4uSDiY3fv7N34VXOI6YVSbx0aqoV9gcwHkcLiTlSl199F+PuNhjwRgYzyZXwQw6arkLP/S3y1QurSyVpRMf5ZPMNshLBm2hqgz3Pa9DELhNnwBtX7l4r++ItQ4cXurIAcR8BFhRogtGxD7/6WyUduH3Nr+ytyww3Vn5DXBqr0vVmjyQ0vxYreNPgHZZsiYJJiL4t0puflxNu3bhgz6RJlS0JrloRzn0rqkWQcnUPbpQv3KejjYRAk3Nn7k+HayE8hJJvUS7oeeBiEsHAlaVoto4gkFlnXGWZjAyAGp3gYOq0hjubFFKZWc/lUohjS5Os6K8g5GJf94yiscUM67XJ1BJBj1z4ImamW+J/1Rwq6t48PdsioDw9G4JmHFY70Dt99FrVNvPoGYxuqzM2XablxKHjKlgcDhxXnrQT0G3pFh0ckiEf3NNaV+1SCIDYdQxTKpudi00/TkxunbEFPK2mDPZ1GSRTV6IHv25q0MuZT7QUF2TvRyP8Q/yaRcnlvpQam8XuEVkmT+RL1bSynnvQ95tOYWHP1YjaVAU++8nRKeKIJytX6zuKNupDVldeHSSgIZe5m6cKyFTZ7d5Yr7ASFNSPoTk7NCVXDtvlYmEUgIlTdmqDXHZn7K0QXUiIyal414/E/QVFjcKJVIlpgR4+n8yFqPKCfiVA4A44FJoTFJotazuIrDklsbXQ4Svstfv56A7mK9ATBScWsGF3pdCZTFZyT2xE3JoKWKaaYeULyjQMNwkQhoM+jHI0d79BaUo1vlDdfU4QKFnc3stcqz4VaKW05/G2s0gkT8TPSHxSdpu5F0QjZtp+NKu7wRfWLKcj/rY+6NuHQf/tTwpGnn7fXjkEtlyJKXT070xbP0DJzvzBZLsJEceAfHK3n8ujPi4DWBOeevzV7Fqt4o/8jceADS4DZHSc7Kv0L1MNFG/vYK0zHnhWLtCxM8UetKcsLg6YTiSThB5fEKEf2HcEKx6G0PmcQ1dknGS4KzAoekqcQ2KQwH5PH74hbqFl7amPPVtnscdsv4QYWs0GfHKhlTr3AbUwk2OmYceMoVLYFIJgiGgkIphG8/JxLg3LmismzWSknClWOQsj+qDdJo8Snsm0ffDOu21oPvhsaqm11LdHSXXK7bM8xoHVXHhZGfkYl07nkwIuxfz2C/azuysizUgsn5hLoxawDFejgNAc/Vj87TdJBp+5grhdI0dlptICJ5fDR4KU3LEYnoiuZtGwjJKeMjlPKNpLyh9+Q/5g6kGd6d2kg3PvHHtbZDDW/ihulV7uvQ8dwxFU4zg2TYLxkDHr39AIn7bJP5HiC4GeupHQ+uRn6IncN88YcSJf4slgwySOm/xz9Nunfy7fLuamyZEIt0gHET+iktIP7fbPwTDPCWQV1Fl5pwmjNVqMn3g74ijvhOeW3dALCHt1dUPbu8byhIHM4rS6YqG+HWhlzE3mjF67yIFYPxd18/5nwmaPzR/DzU+LwGQY7zmFRUt5KwYVTYIEi/KeGIcvzY15ZOg3OpqBldskwM41WqvOnbVFevgAruAkB7g1r6lqlsYr52y9xpc+CPNRKXZ5i743apCMii79gq5RalE/aSokkc2Dt82cxcuf1tmHXUDGrRlrwW/tqsmnhe1FUzrxg1mDF8pmoGO/AP+kYf9WWLj3WQPIMLEtfYi4H/cbyDvtCaMZviU4u3JjC2Imct95JOeY4KiU1l+zT09W0O2qa1mg7wZb646IWshsZO+fEcn7w6fIEkmLcF2ySlM1WvcPkF4cj+2CVLmXz6h+I+4aCB+T737Km/Hfadrhqeh+Oo0VOimxvkk4VyOMN3F+8KpIY6YxJ8ug0ogjyifGJ9aTMGS8xx6sCVHpyj8C64Iw98IrbcZYrzNn4tuyY9Q+BymiQHrLg7OAKXzIwm/XvyOLMwaZ2rl6YuBMd2xjw22QUrHP0vXXx3Cx8OJgxn7Rlqjy+tuBMdjyyg6DGqd6s9/obnrT/MDjvHscJZkOMdQc4X6+EOR5cBeSgdMHHQkl1ed9Ugkv0tT2f7dqp54GkWHu3ueaADmuEzKdZ1j+/x6a5hPxb0rdVBNu0DYgjlxCSMJb2g53N5iIKSgfhMrOv/fk4Gfjlm3tCRq22hdXugfF32B2UMN7kbskvpwgqR4tHlHxqCxiWqPmM0ORKFn4hsMBMEYxdJbK3OiTsgx9k5hJxVAf5e76mEfk5fNaRazrOkKmn3q8/rdteRwew7etgJICKx7M8oRCQ/hx4Re7vHJddmI5WWy62yby7U80f8SiYAO59zGSBsHU299Ez6yk+sTGZbnZ9naWANEunO0J23h/3ksNha9zorBvqH8bImEza/5pF8Es1Zr5SCLPMps8S8wqbVDom03tkGKrlAGEwhhmoB9QI+u8YhYcy7MUyieUBFTWbza1zjlFcRrjZCG8hfyrudlHTot5pIOIs/P+3mqeUSFEVsBN+P7AiUH8iUQmGwMRDj0xQ5myd+xdRMpfvNFoIs4ejekhR/MF+WQF03eeqB/qu0j49M+zcSU3WGQiVvldBE8LuWR8g28tXuCfRHE1MGqZwYSn0ah5pVYpLNZQPSJE8Gj9r9eA98g6wIlgYb1aUpD1T+Z7bqAZJoFpmVRuTtmdC0pqOTmFc8w/+c9gEiQUeBeA9BMSH2Wd2yk3LJXf4wN4qGK/iJWeGvhf9Tk1+2eOPusoMkGqGh6zETjMzyZh1KdYFSoLT5+wrE69CFpqcWNfwW3q2U+gg0Ea1B9+95l8Z17DqabwTQE2EfqidTQw1zM8zSnjaNo0oyXQzt7Gd5UwXUCCQQQlk9QRMIFDfoZH71Z6ns/P/AlALFPN7XrChc4t7HnXMUDrtM33IueNHKarySYXA8DhyZb8iOdslUkqRFsiz1RV/LXBEGqy+syPHg3hVH4xpAvF0qwMe3u4ZAnCzHKZ0SP8Yac35TtUlMWGnWvqfdAUjtjGHAJMugJpuuB90EtPVEp34m/02A2/Wil9DSd2I+o521Y1Ua2qwxDccED8286ArKs6KqU16+1P6Mi7CiYleAUPGiaU7btN9SXd6xmUwFmiUIDoV3+7xCgj/EblczAVgJZpU+gWU5zYj3j9rbKMDTFFURu8QBXJOFXwziuYGDIRuuqqIs6M0bbukX6m7MsJzKtFV4ohCp23IIfrpX54J6U0ZGnpf2rGwR/O5mSkmxeMPFwEwGyeg7XMD6YX9jG3570prcaxCcQK1sbwWk+CmaaThsRMU/rwmoV3sLP8d/cazKwKQspe9CsIVE+YUt6xmX2SBKNaJgz//IDaydbOqBA+bt/qF2bnOfypKugAbw8fhdwXKZ0cCAG3wlciJjyVflehvNp81ZyCMLEvYRBToFZ7xfE35XY7SF47UF2edNM9cQQW/3adv5WhEZua1aMu6oKV+tB+bqZX0wrAjY5KYOBuE5VtDu+5KF6pboOLOEXX6yDmVAVrp1HL1utW1Ujpo9bCt01FNQYjwfvb9QunGxKDZg06BfL75pfb70aYL99dCg9hERz2BW3CZeFX0SMvQqqQtRl+9dv52ExFL2xBFs3BgB/4COAxwvk2l9eRQ109Ocp5PibCcQOUIRwH5zlZTsDDpKFgU9oOp9ot77xxIiplIsz1jTfkKVJZjZDoP2wMwey9q5H/8ZkElxDczwT1ld33p6rhWd8HJ0EX+x4GZTLsVR4WMrGUl6YqO3+uWKTFOTVtV2cDGTw6acP9sENfP1TSdvqJ2/pQ7MttP39TC7XDnLw31zrPE3nTXn9rgTiZUkEp2oGPkFseukDWZheO3fE13NdjI63+KXKouRuxKLPKr3tchqHDDuRBPCD6YKzYKOwVPlyVjT+sPebMILbzOdqf6Dt9odzs0FT9dK86DDWA8Y7cHx5IE00T5eYV3qepAXEwK25Q636amR7wjIqfgiyZB5Ayh8DjgmDGcGRsqMsWdIU4WhoLm6BltC9nsjdyWNDQMYv2aCaEPuDYwF55m++ly1MEAY3lFGWY+kAXOsWTURb6REWSJwHmnX9p0HFBLzp1yCJBfSvCSR5YjK1jHcFHQwHp9fB562qGPmrSQOcntxdWGBI5cXM4Hpb1fJ6sbyBMx8aQp/iWmrLMPGlrfnnreg95sV8g/wi1NtqnxiiHx/oVUhDPNuJvfzU537/1MrT2zNS4e34WP3YdGTuGpXEEYMqKrzumwiY/8XV0DxWXdzdk9576u0xRZE74lKc9L4j+Z7LAn52GRgAJr6boKRxEyjvVN1o8rNwErRfyKRZU//hpwpEnc7hl7AUh23U4URdhVbBVfwESRw0t54K3uza1LWeeEZcl5yy6B1R7wVvPwkgPk9eOIhu6ZzFgtVZd2u7a+46OmV4lZ141Rgt/ZLMdVmI0xARrnUoWvR1t2XGPLTBWPykrqTI5bkTei0YaKiCSmzTlcuQkLFzU0YdNuEcYZUrtVnnMgsRzksdDAAhrZaZ18fmBKDWgOj8qYijzvJ3nXcHNMOLsJ/DB1bvzT+E3X2GD+Hf33kfK6vjasajPfc3+KRb3gNXjQEM42kD0bZ5cRegIdOzbi/9ICdIa3lUD+E1xEG5zzaq83WGnRUJ8oY3vXoiCIa+rwsMWud+6NItrCr7n0KfdBRPBneHkVDa2FmE9eqYu0jDqCBAlga9sYcYNHiz3BGSO3B5J0P8KonS9COpaJxoNMhrT4w6hzOpbooX2gk4EBXk7LOF2mJRggvGqMqWiUQrWhjBRxUtHzCXphV3xXmD82gWsf/JUe0zJmCmzgkYCD/DgNfJMvtJnGyKvCXnKsBwXhRJdMW+TUpC0SGgh2r4AkiEwevIXXRnrtI2KQRh5H22rTGJ8PXJFLoIzytLJy+uGyoP+Xwit4jiKeyncJbQnAP6Q5tmgWXRBDG+kswbo5n0o9n+tSQReJngszh4qEcCqT+ttAH4h2sNlfj/5/DaU19vP25lQoTrbEiQ718EHaVIkAHI2D0fZZxUq3r+aVjjME0hNxm4wHcAEHV6MTXyGRdoZe/uolB4Vhym7Ck60+3YVsnQ/+7kZUIbLpvsBb4Ecn5BaXvTm3gcVvYMEEscnOMODvjoKaH7OcvlZAqSNR4VKQUHEiXTzSLOVPWil249W2sQdgkG+eIPRM/9y1KXniNH56HeaOwPm3yZGZQE6TSm6+OJyCAidg7RA05TKehhAyOwDbZ2AB2xqGJ53BkGXmf5FF1Ud3+9d8q8/vTwGoVVsxhBlDHW/+z666zJpIn+8Bk50dq4JDmeVcbh+137EWVRqco/mH/4WoHojzp7QRkC0Px1RNF0uv/Z5I1lQMh30U+hNh/AS4jvbWgr5aQAgzLixEAJfklMPyADGnUMJ3Dr3FXprlOYx1MVWk7OmJGQ29O86enj2K07Me9pcQKveHGiltzT1LFQ3tppDjjnrIuI1qboRnsM9diJFt2TtpB6oZxLy/3dmZ70BCIxNenUwR0gTPs24fSk/0Hc2KopeljSDE5QiQLRsBRpxDrmi3HPj/xvyGBGF0FQmSmOxsStGdi8RX5jXDpxFDpc7oLehQHQfa+KzfeUoY0haZVTJtWRVud72vGOVbEYPlRYrum795iF5T1F3dAJ4q3ZJY9rsX/OJuFXGUVKBAk6r6jnMPRaT8S04ao2kE/ZHZk0qoiqaYe7WG2Xe9O0WZf02WAWzO1vYc+8qKgJBP7xRgzrh/taKegdkOqGzhsno6dnGorUWe/3m1lTYgnm7dtm/YoyotE66gdqCgDFFkSHzXPuPGrkTfybmF9zz+8hVmGdECgwCRbEV/W/Mk1lDsfyie02PtgFHAAAIdg2oV1amXSYVZllQX9TH0cfwpa9tYKMQXUWKECacwPe0naZwVF7GTeQT7jaZeSX8uDqmA20jTd1w++pk+z1CI1eR5dsAeqO19qBnuLGXOx1GWQVd8Si3n3orJgIt39onvaLlYtNkmIzU3vvAG1FeI5ugGZdGu1hyKKyIoHq6hkwlJp8X45eR/XZtbgg/e7peizLtliSr9XXDrafKYZ3hic4h8NXPIXtDfDY3poP2mPTIBvR3GEmvOho11SDCvb1IkYGXWQDbUXTCG9InprKum1CuM6zmn+E7N8pl9nV+SwUbp6UhbHCcgdu/twJghHrgC312io4LcoxOGr657rZXs7S3cMd5syMmx5TmvIOM53KH3gskdJ7jw4vWMyxqwlsaPwvNzW2bYK0QAsTB7WpGQJdzUsaXkzbHZD8n2XWB5RkiqQTUhl+kVyE6+ebiMEaVje6E3Nietc1R/u8NMAXAMTm61Zw8PGYajf+R9+AXALoXqGygKkXJ1gEOPLSjKs81bxM1VzRsULRe7wzLRLc6x+PJaCSImqUV4AMxPUoYiqRoU+budLsBwmdyOiC6Zr+NMPQE5add3kpXw+yZOB4jEeCgKMZV3WzYXJ5R0tHhN/OWwin6xHGBlMTcA1HHWIgSfpHN/djbqN3iYnlcrMZXRv1VdnNvaJuXuTMdwzy401zglVarfWrJ5o2k+tcirXoxoNdDygqLI573oZGcG8BcNdNo6bksVKfQTkTowIGGdM0kZ+775sM/asOKkURiQfvyBiYc5narwv3ztzXAsM0L4aam/sxHEGm4ejqwGKcC5/ZtPrjFdnnH/60M1A2kjUTkxpEnqL0pnhAxElfRWHSBGMt4pNMH7ddDCKUEjIz8D5ngZ+Keg7dOW6x9rszhhv8doKZPBAJUL4v8ACuXqGHnGEj4N/w5ZJ1/Ixwcw7ezVhj9/ZJqLrDeEQGFItwUEUD1pEucJhGYggDEPV9H+VDaB8YniwGETAPNq56vcCuF8dsKwQBqbau5gw8rReXe1H9yznqOpZvxmBz6OsmxLnkfNqGF8Pgxcp6QgWUcIhdN7X1yTZKecBA6KolghZ7/x+faTOkL1Xpz4W8qHtATxW+pGv9/Gae99AQYVYdLg14z6Nn6f/wwGtN+Q=";

// App State Manager
class ReqGatherApp {
    constructor() {
        this.modules = [];
        this.cryptoKey = null;
        this.activeModuleId = null;

        // Dom Elements
        this.cardsGrid = document.getElementById('cards-grid');
        this.drawer = document.getElementById('drawer');
        this.drawerOverlay = document.getElementById('drawer-overlay');
        this.btnCloseDrawer = document.getElementById('btn-close-drawer');
        this.drawerTitle = document.getElementById('drawer-title');
        this.drawerSubtitle = document.getElementById('drawer-subtitle');
        this.drawerIcon = document.getElementById('drawer-module-icon');
        this.focusList = document.getElementById('focus-list');
        this.toast = document.getElementById('toast');

        // Custom Focus Area input elements
        this.inputNewFocusName = document.getElementById('input-new-focus-name');
        this.btnAddCustomFocus = document.getElementById('btn-add-custom-focus');

        // Modal
        this.exportModal = document.getElementById('export-modal');
        this.btnExportMd = document.getElementById('btn-export-md');
        this.btnExportCsv = document.getElementById('btn-export-csv');
        this.btnCloseExportModal = document.getElementById('btn-close-export-modal');
        this.exportPreviewContent = document.getElementById('export-preview-content');
        this.btnCopyPreview = document.getElementById('btn-copy-preview');
        this.btnDownloadPreview = document.getElementById('btn-download-preview');

        // Add Custom Module Modal elements
        this.addModuleModal = document.getElementById('add-module-modal');
        this.inputModuleTitle = document.getElementById('input-module-title');
        this.inputModuleDesc = document.getElementById('input-module-desc');
        this.btnConfirmAddModule = document.getElementById('btn-confirm-add-module');
        this.btnCancelAddModule = document.getElementById('btn-cancel-add-module');
        this.btnCloseAddModuleModal = document.getElementById('btn-close-add-module-modal');

        // JSON backup/restore
        this.btnExportJson = document.getElementById('btn-export-json');
        this.btnImportJson = document.getElementById('btn-import-json');
        this.importFileInput = document.getElementById('import-file-input');

        // Reset
        this.btnReset = document.getElementById('btn-reset-data');

        // Suppressed Items elements
        this.suppressedSection = document.getElementById('suppressed-items-section');
        this.suppressedHeader = document.getElementById('suppressed-items-header');
        this.btnToggleSuppressed = document.getElementById('btn-toggle-suppressed');
        this.suppressedListEl = document.getElementById('suppressed-list');
        this.suppressedCountEl = document.getElementById('suppressed-count');
        this.isSuppressedExpanded = false;

        // Login Screen elements
        this.loginScreen = document.getElementById('login-screen');
        this.loginForm = document.getElementById('login-form');
        this.loginError = document.getElementById('login-error');
        this.usernameInput = document.getElementById('username');
        this.passwordInput = document.getElementById('password');
        this.btnLogout = document.getElementById('btn-logout');

        this.init();
    }

    async init() {
        this.setupEventListeners();
        await this.checkAuth();
    }

    // Sanitize and migrate legacy priorities
    sanitizeData(modules) {
        modules.forEach(mod => {
            mod.items.forEach(item => {
                if (!item.criticality) {
                    item.criticality = "normal";
                }
                if (item.suppressed === undefined) {
                    item.suppressed = false;
                }
                // Convert legacy high/med/low priorities to phase1/phase2/future
                if (item.priority === 'high') {
                    item.priority = 'phase1';
                } else if (item.priority === 'med' || item.priority === 'medium') {
                    item.priority = 'phase2';
                } else if (item.priority === 'low') {
                    item.priority = 'future';
                } else if (!item.priority) {
                    item.priority = 'phase2';
                }
            });
        });
        return modules;
    }

    // Merge loaded modules with default template structures
    mergeDefaultStructures(loadedModules, defaultModules) {
        defaultModules.forEach(defaultMod => {
            let loadedMod = loadedModules.find(m => m.id === defaultMod.id);
            if (!loadedMod) {
                // Module doesn't exist in loaded data, copy it completely
                loadedModules.push(JSON.parse(JSON.stringify(defaultMod)));
            } else {
                // Module exists, check its items
                const defaultItems = defaultMod.items;
                const loadedItems = loadedMod.items;
                const mergedItems = [];

                // Reorder and merge default items
                defaultItems.forEach(defaultItem => {
                    const loadedItem = loadedItems.find(i => i.id === defaultItem.id);
                    if (loadedItem) {
                        // Update default fields to latest templates
                        loadedItem.name = defaultItem.name;
                        loadedItem.guidance = defaultItem.guidance;
                        mergedItems.push(loadedItem);
                    } else {
                        // Item is new, copy it
                        mergedItems.push(JSON.parse(JSON.stringify(defaultItem)));
                    }
                });

                // Append user's custom items
                loadedItems.forEach(loadedItem => {
                    if (loadedItem.id && loadedItem.id.startsWith('custom-')) {
                        mergedItems.push(loadedItem);
                    }
                });

                loadedMod.items = mergedItems;
                loadedMod.title = defaultMod.title;
                loadedMod.description = defaultMod.description;
                loadedMod.icon = defaultMod.icon;
            }
        });

        return loadedModules;
    }

    // Load from local storage or set defaults
    async loadData(decryptedDefault) {
        const savedData = localStorage.getItem('mrp_requirements_data');
        const defaultModules = JSON.parse(decryptedDefault);
        if (savedData) {
            try {
                const decryptedJson = await decryptWithKey(savedData, this.cryptoKey);
                let loadedModules = JSON.parse(decryptedJson);
                this.modules = this.mergeDefaultStructures(loadedModules, defaultModules);
                await this.saveData();
            } catch (e) {
                console.error("Failed to decrypt or parse saved data. Reverting to default.", e);
                this.modules = defaultModules;
            }
        } else {
            this.modules = defaultModules;
        }

        this.sanitizeData(this.modules);
    }

    // Save to local storage
    async saveData() {
        if (!this.cryptoKey) return;
        try {
            const jsonString = JSON.stringify(this.modules);
            const encryptedBase64 = await encryptWithKey(jsonString, this.cryptoKey);
            localStorage.setItem('mrp_requirements_data', encryptedBase64);
            this.updateOverallProgress();
            this.renderCards();
        } catch (e) {
            console.error("Failed to encrypt and save data", e);
        }
    }

    // Show save toast
    showToast(message = "Changes saved!") {
        this.toast.textContent = message;
        this.toast.classList.add('show');
        setTimeout(() => {
            this.toast.classList.remove('show');
        }, 2000);
    }

    // Calculate progress indicators
    updateOverallProgress() {
        let totalItems = 0;
        let scopedItems = 0;

        this.modules.forEach(mod => {
            mod.items.forEach(item => {
                if (item.suppressed) return; // Skip suppressed items
                totalItems++;
                if (item.scope !== "pending") {
                    scopedItems++;
                }
            });
        });

        const percentage = totalItems > 0 ? Math.round((scopedItems / totalItems) * 100) : 0;

        // Update DOM
        document.getElementById('overall-percentage').textContent = `${percentage}%`;
        document.getElementById('overall-progress-bar').style.width = `${percentage}%`;
        document.getElementById('completed-stats').textContent = `${scopedItems} of ${totalItems} items scoped`;
    }

    // Render main cards
    renderCards() {
        this.cardsGrid.innerHTML = '';

        this.modules.forEach(mod => {
            const card = document.createElement('div');
            card.className = 'mrp-card';
            card.dataset.id = mod.id;

            // Calculate progress for card
            const activeItems = mod.items.filter(item => !item.suppressed);
            const total = activeItems.length;
            const scoped = activeItems.filter(item => item.scope !== "pending").length;
            const progressPercent = total > 0 ? Math.round((scoped / total) * 100) : 0;

            card.innerHTML = `
                <div class="card-top">
                    <div class="card-icon-wrapper">
                        ${mod.icon}
                    </div>
                    <h3>${mod.title}</h3>
                    <p class="card-desc">${mod.description}</p>
                </div>
                <div class="card-bottom">
                    <div class="card-progress-bar" title="${progressPercent}% Complete">
                        <div class="card-progress-fill" style="width: ${progressPercent}%;"></div>
                    </div>
                    <span class="card-badge">${scoped}/${total} scoped</span>
                </div>
            `;

            card.addEventListener('click', () => this.openDrawer(mod.id));
            this.cardsGrid.appendChild(card);
        });

        // Append the special "+" card for adding custom modules
        const addCard = document.createElement('div');
        addCard.className = 'mrp-card add-card-trigger';
        addCard.innerHTML = `
            <div class="card-add-icon">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" style="width: 24px; height: 24px;">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                </svg>
            </div>
            <h3>Add Custom Module</h3>
            <p class="card-desc">Create a new business module card to gather customized requirements.</p>
        `;
        addCard.addEventListener('click', () => this.openAddModuleModal());
        this.cardsGrid.appendChild(addCard);
    }

    // Slide in drawer and load focus areas with morphing animation
    openDrawer(moduleId) {
        this.activeModuleId = moduleId;
        const mod = this.modules.find(m => m.id === moduleId);
        if (!mod) return;

        this.drawerTitle.textContent = mod.title;
        this.drawerSubtitle.textContent = `Gathering requirements for: ${mod.title}`;
        this.drawerIcon.innerHTML = mod.icon;

        // Remove existing delete module button if any
        const existingDeleteBtn = this.drawer.querySelector('.btn-delete-module');
        if (existingDeleteBtn) {
            existingDeleteBtn.remove();
        }

        // If it's a custom module, insert a delete button in the header
        if (moduleId.startsWith('module-custom-')) {
            const deleteBtn = document.createElement('button');
            deleteBtn.className = 'btn-delete-module';
            deleteBtn.innerHTML = `
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="width: 14px; height: 14px;">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                </svg>
                Delete Module
            `;
            deleteBtn.addEventListener('click', () => this.deleteCustomModule(moduleId));

            // Insert it before the close button
            const closeBtn = document.getElementById('btn-close-drawer');
            closeBtn.parentNode.insertBefore(deleteBtn, closeBtn);
        }

        this.renderDrawerFocusItems();
        this.updateDrawerSummaryStats();

        // Get clicked card element
        const cardEl = document.querySelector(`.mrp-card[data-id="${moduleId}"]`);
        if (cardEl) {
            const rect = cardEl.getBoundingClientRect();

            // Set initial style matching clicked card (rotated in 3D space)
            this.drawer.style.transition = 'none';
            this.drawer.style.top = rect.top + 'px';
            this.drawer.style.left = rect.left + 'px';
            this.drawer.style.width = rect.width + 'px';
            this.drawer.style.height = rect.height + 'px';
            this.drawer.style.borderRadius = '16px';
            this.drawer.style.transform = 'perspective(1500px) rotateY(-180deg) rotateZ(12deg) scale(0.9)';

            // Force reflow
            this.drawer.offsetHeight;

            // Set final expanded style with transition (flips and straightens, centered)
            this.drawer.style.transition = 'all 0.8s cubic-bezier(0.175, 0.885, 0.32, 1.1), visibility 0s linear 0s';
            if (window.innerWidth <= 600) {
                this.drawer.style.top = '0';
                this.drawer.style.left = '0';
                this.drawer.style.width = '100vw';
                this.drawer.style.height = '100vh';
                this.drawer.style.borderRadius = '0';
            } else {
                this.drawer.style.top = '5vh';
                this.drawer.style.left = '10vw';
                this.drawer.style.width = '80vw';
                this.drawer.style.height = '90vh';
                this.drawer.style.borderRadius = '24px';
            }
            this.drawer.style.transform = 'perspective(1500px) rotateY(0deg) rotateZ(0deg) scale(1)';
        }

        this.drawer.classList.add('open');
        this.drawerOverlay.classList.add('open');
    }

    closeDrawer() {
        if (!this.activeModuleId) return;

        const cardEl = document.querySelector(`.mrp-card[data-id="${this.activeModuleId}"]`);
        if (cardEl) {
            const rect = cardEl.getBoundingClientRect();

            // Transition back to card boundary, twisting in reverse
            this.drawer.style.transition = 'all 0.8s cubic-bezier(0.175, 0.885, 0.32, 1.1), visibility 0s linear 0.8s';
            this.drawer.style.top = rect.top + 'px';
            this.drawer.style.left = rect.left + 'px';
            this.drawer.style.width = rect.width + 'px';
            this.drawer.style.height = rect.height + 'px';
            this.drawer.style.borderRadius = '16px';
            this.drawer.style.transform = 'perspective(1500px) rotateY(180deg) rotateZ(-12deg) scale(0.9)';
        }

        this.drawer.classList.remove('open');
        this.drawerOverlay.classList.remove('open');

        this.activeModuleId = null;

        // Clean up inline styles after transition finishes
        setTimeout(() => {
            if (this.activeModuleId === null) {
                this.drawer.style.transition = '';
                this.drawer.style.top = '';
                this.drawer.style.left = '';
                this.drawer.style.width = '';
                this.drawer.style.height = '';
                this.drawer.style.borderRadius = '';
                this.drawer.style.transform = '';
            }
        }, 800);
    }

    updateDrawerSummaryStats() {
        const mod = this.modules.find(m => m.id === this.activeModuleId);
        if (!mod) return;

        const activeItems = mod.items.filter(item => !item.suppressed);
        const inScope = activeItems.filter(i => i.scope === 'in').length;
        const niceHave = activeItems.filter(i => i.scope === 'nice').length;
        const outScope = activeItems.filter(i => i.scope === 'out').length;
        const pending = activeItems.filter(i => i.scope === 'pending').length;

        document.getElementById('mod-in-scope').textContent = inScope;
        document.getElementById('mod-nice-have').textContent = niceHave;
        document.getElementById('mod-out-scope').textContent = outScope;
        document.getElementById('mod-pending').textContent = pending;
    }

    renderDrawerFocusItems() {
        this.focusList.innerHTML = '';
        this.suppressedListEl.innerHTML = '';

        const mod = this.modules.find(m => m.id === this.activeModuleId);
        if (!mod) return;

        const activeItems = mod.items.filter(item => !item.suppressed);
        const suppressedItems = mod.items.filter(item => item.suppressed);

        // Update suppressed section visibility and count
        if (suppressedItems.length > 0) {
            this.suppressedSection.style.display = 'block';
            this.suppressedCountEl.textContent = suppressedItems.length;
        } else {
            this.suppressedSection.style.display = 'none';
        }

        if (activeItems.length === 0) {
            this.focusList.innerHTML = '<p class="text-secondary" style="font-size: 0.9rem; text-align: center; padding: 2rem;">No items yet. Add custom focus items below.</p>';
        } else {
            activeItems.forEach(item => {
                const card = document.createElement('div');
                card.className = 'focus-item-card';
                card.dataset.itemId = item.id;

                const isCustom = item.id.startsWith('custom-');

                card.innerHTML = `
                    <div class="focus-item-top">
                        <div class="focus-item-info">
                            <h4>${item.name}</h4>
                            ${isCustom ? '<p class="sub-detail">Custom Focus Area</p>' : ''}
                        </div>
                        <div class="focus-item-actions">
                            ${isCustom ? `
                                <button class="btn-delete-custom" title="Delete custom focus item" data-item-id="${item.id}">
                                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                    </svg>
                                </button>
                            ` : ''}
                            <button class="btn-suppress-item" title="Suppress requirement" data-item-id="${item.id}">
                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                                </svg>
                            </button>
                        </div>
                    </div>
                    <div class="focus-controls">
                        <div class="control-group">
                            <label>Scope Status</label>
                            <div class="scope-selectors" data-item-id="${item.id}">
                                <button class="scope-pill ${item.scope === 'in' ? 'active' : ''}" data-scope="in">In Scope</button>
                                <button class="scope-pill ${item.scope === 'nice' ? 'active' : ''}" data-scope="nice">Nice-to-Have</button>
                                <button class="scope-pill ${item.scope === 'out' ? 'active' : ''}" data-scope="out">Out of Scope</button>
                            </div>
                        </div>
                        <div class="control-group">
                            <label>Priority</label>
                            <div class="priority-selectors" data-item-id="${item.id}">
                                <button class="priority-pill ${item.priority === 'phase1' ? 'active' : ''}" data-priority="phase1">Phase 1</button>
                                <button class="priority-pill ${item.priority === 'phase2' ? 'active' : ''}" data-priority="phase2">Phase 2</button>
                                <button class="priority-pill ${item.priority === 'future' ? 'active' : ''}" data-priority="future">Future</button>
                            </div>
                        </div>
                        <div class="control-group">
                            <label>Criticality</label>
                            <select class="criticality-select" data-item-id="${item.id}" data-val="${item.criticality || 'normal'}">
                                <option value="super" ${(item.criticality || 'normal') === 'super' ? 'selected' : ''}>Super Critical</option>
                                <option value="critical" ${(item.criticality || 'normal') === 'critical' ? 'selected' : ''}>Critical</option>
                                <option value="normal" ${(item.criticality || 'normal') === 'normal' ? 'selected' : ''}>Normal</option>
                            </select>
                        </div>
                    </div>
                    ${item.guidance ? `
                    <div class="guidance-box">
                        <div class="guidance-header-row">
                            <div class="guidance-title">Guidance Prompt</div>
                            <button class="btn-copy-guidance" data-item-id="${item.id}" title="Copy guidance to notes">
                                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" style="width: 11px; height: 11px; margin-right: 2px;">
                                    <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                                    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                                </svg>
                                <span>Copy to Notes</span>
                            </button>
                        </div>
                        <div class="guidance-text">${item.guidance}</div>
                    </div>` : ''}
                    <div class="notes-wrapper">
                        <label>Specific Requirements & Notes</label>
                        <textarea class="notes-textarea" data-item-id="${item.id}" placeholder="Write notes, volume estimations, existing vendor details or specific requirements here...">${item.notes || ''}</textarea>
                    </div>
                `;

                // Bind selectors events
                const pills = card.querySelectorAll('.scope-pill');
                pills.forEach(pill => {
                    pill.addEventListener('click', (e) => {
                        const scope = e.target.dataset.scope;
                        this.updateItemScope(item.id, scope, pills);
                    });
                });

                // Bind priority pills events
                const priorityPills = card.querySelectorAll('.priority-pill');
                priorityPills.forEach(pill => {
                    pill.addEventListener('click', (e) => {
                        const priority = pill.dataset.priority;
                        this.updateItemPriority(item.id, priority, priorityPills);
                    });
                });

                // Bind copy guidance button
                const btnCopyGuidance = card.querySelector('.btn-copy-guidance');
                if (btnCopyGuidance) {
                    btnCopyGuidance.addEventListener('click', () => {
                        this.copyGuidanceToNotes(item.id);
                    });
                }

                // Bind criticality change
                const critSelect = card.querySelector('.criticality-select');
                critSelect.addEventListener('change', (e) => {
                    const criticality = e.target.value;
                    this.updateItemCriticality(item.id, criticality, critSelect);
                });

                // Bind notes textarea input with simple autosave / blur event
                const textarea = card.querySelector('.notes-textarea');
                textarea.addEventListener('blur', (e) => {
                    this.updateItemNotes(item.id, e.target.value);
                });
                textarea.addEventListener('input', (e) => {
                    // Autosave helper to avoid losing content if closed
                    this.updateItemNotesSilent(item.id, e.target.value);
                });

                // Bind custom delete buttons
                if (isCustom) {
                    const btnDel = card.querySelector('.btn-delete-custom');
                    btnDel.addEventListener('click', () => {
                        this.deleteCustomFocus(item.id);
                    });
                }

                // Bind suppress button
                card.querySelector('.btn-suppress-item').addEventListener('click', () => {
                    this.suppressItem(item.id);
                });

                this.focusList.appendChild(card);
            });
        }

        // Render suppressed items
        suppressedItems.forEach(item => {
            const row = document.createElement('div');
            row.className = 'suppressed-item-row';
            row.dataset.itemId = item.id;

            const isCustom = item.id.startsWith('custom-');

            row.innerHTML = `
                <div class="suppressed-item-info">
                    <h5>${item.name}</h5>
                </div>
                <div class="suppressed-item-actions">
                    <button class="btn-restore-item" data-item-id="${item.id}">Restore</button>
                    ${isCustom ? `
                        <button class="btn-delete-suppressed" title="Delete custom focus item" data-item-id="${item.id}">
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                            </svg>
                        </button>
                    ` : ''}
                </div>
            `;

            // Bind restore
            row.querySelector('.btn-restore-item').addEventListener('click', () => {
                this.restoreItem(item.id);
            });

            // Bind delete if custom
            if (isCustom) {
                row.querySelector('.btn-delete-suppressed').addEventListener('click', () => {
                    this.deleteCustomFocus(item.id);
                });
            }

            this.suppressedListEl.appendChild(row);
        });
    }

    suppressItem(itemId) {
        const mod = this.modules.find(m => m.id === this.activeModuleId);
        if (!mod) return;

        const item = mod.items.find(i => i.id === itemId);
        if (!item) return;

        item.suppressed = true;
        this.saveData();
        this.renderDrawerFocusItems();
        this.updateDrawerSummaryStats();
        this.showToast(`Suppressed "${item.name}"`);
    }

    restoreItem(itemId) {
        const mod = this.modules.find(m => m.id === this.activeModuleId);
        if (!mod) return;

        const item = mod.items.find(i => i.id === itemId);
        if (!item) return;

        item.suppressed = false;
        this.saveData();
        this.renderDrawerFocusItems();
        this.updateDrawerSummaryStats();
        this.showToast(`Restored "${item.name}"`);
    }

    toggleSuppressedList() {
        this.isSuppressedExpanded = !this.isSuppressedExpanded;
        if (this.isSuppressedExpanded) {
            this.suppressedListEl.style.display = 'flex';
            this.btnToggleSuppressed.classList.add('expanded');
            this.btnToggleSuppressed.querySelector('.toggle-text').textContent = 'Hide';
        } else {
            this.suppressedListEl.style.display = 'none';
            this.btnToggleSuppressed.classList.remove('expanded');
            this.btnToggleSuppressed.querySelector('.toggle-text').textContent = 'Show';
        }
    }

    updateItemScope(itemId, scopeVal, pills) {
        const mod = this.modules.find(m => m.id === this.activeModuleId);
        if (!mod) return;

        const item = mod.items.find(i => i.id === itemId);
        if (!item) return;

        // Toggle logic: click active scope pill again resets it to pending
        if (item.scope === scopeVal) {
            item.scope = "pending";
        } else {
            item.scope = scopeVal;
        }

        // Update pills styling
        pills.forEach(p => {
            p.classList.remove('active');
            if (p.dataset.scope === item.scope) {
                p.classList.add('active');
            }
        });

        this.saveData();
        this.updateDrawerSummaryStats();
        this.showToast(`Scope updated for ${item.name}!`);
    }

    updateItemPriority(itemId, priorityVal, pills) {
        const mod = this.modules.find(m => m.id === this.activeModuleId);
        if (!mod) return;

        const item = mod.items.find(i => i.id === itemId);
        if (!item) return;

        item.priority = priorityVal;

        // Update pills active styling
        pills.forEach(p => {
            p.classList.remove('active');
            if (p.dataset.priority === item.priority) {
                p.classList.add('active');
            }
        });

        this.saveData();
        this.showToast(`Priority updated for ${item.name}!`);
    }

    copyGuidanceToNotes(itemId) {
        const mod = this.modules.find(m => m.id === this.activeModuleId);
        if (!mod) return;

        const item = mod.items.find(i => i.id === itemId);
        if (!item) return;

        if (!item.guidance) return;

        // If notes already contains the guidance, don't duplicate
        if (item.notes.includes(item.guidance)) {
            this.showToast("Guidance already in notes!");
            return;
        }

        if (item.notes && item.notes.trim()) {
            item.notes = item.notes.trim() + "\n" + item.guidance;
        } else {
            item.notes = item.guidance;
        }

        this.saveData();

        // Update UI notes textarea if drawer is open
        const textarea = this.focusList.querySelector(`.notes-textarea[data-item-id="${itemId}"]`);
        if (textarea) {
            textarea.value = item.notes;
        }
        this.showToast("Copied guidance to notes!");
    }

    updateItemCriticality(itemId, criticalityVal, selectEl) {
        const mod = this.modules.find(m => m.id === this.activeModuleId);
        if (!mod) return;

        const item = mod.items.find(i => i.id === itemId);
        if (!item) return;

        item.criticality = criticalityVal;
        selectEl.dataset.val = criticalityVal;
        this.saveData();
        this.showToast(`Criticality updated for ${item.name}!`);
    }

    updateItemNotes(itemId, notesText) {
        const mod = this.modules.find(m => m.id === this.activeModuleId);
        if (!mod) return;

        const item = mod.items.find(i => i.id === itemId);
        if (!item) return;

        item.notes = notesText;
        this.saveData();
        this.showToast("Notes saved.");
    }

    async updateItemNotesSilent(itemId, notesText) {
        const mod = this.modules.find(m => m.id === this.activeModuleId);
        if (!mod) return;

        const item = mod.items.find(i => i.id === itemId);
        if (!item) return;

        item.notes = notesText;
        if (this.cryptoKey) {
            try {
                const jsonString = JSON.stringify(this.modules);
                const encryptedBase64 = await encryptWithKey(jsonString, this.cryptoKey);
                localStorage.setItem('mrp_requirements_data', encryptedBase64);
            } catch (e) {
                console.error("Failed to silently save notes", e);
            }
        }
    }

    addCustomFocus() {
        const nameText = this.inputNewFocusName.value.trim();
        if (!nameText) return;

        const mod = this.modules.find(m => m.id === this.activeModuleId);
        if (!mod) return;

        const newItem = {
            id: `custom-${Date.now()}`,
            name: nameText,
            guidance: "Custom focus item added by user.",
            scope: "pending",
            priority: "phase2",
            criticality: "normal",
            notes: ""
        };

        mod.items.push(newItem);
        this.inputNewFocusName.value = '';
        this.saveData();
        this.renderDrawerFocusItems();
        this.updateDrawerSummaryStats();
        this.showToast(`Custom item "${nameText}" added!`);
    }

    deleteCustomFocus(itemId) {
        const mod = this.modules.find(m => m.id === this.activeModuleId);
        if (!mod) return;

        const itemIndex = mod.items.findIndex(i => i.id === itemId);
        if (itemIndex === -1) return;

        const itemName = mod.items[itemIndex].name;
        if (confirm(`Are you sure you want to delete "${itemName}"?`)) {
            mod.items.splice(itemIndex, 1);
            this.saveData();
            this.renderDrawerFocusItems();
            this.updateDrawerSummaryStats();
            this.showToast(`Deleted "${itemName}"`);
        }
    }

    // Export Markdown Report Generation
    generateMarkdown() {
        let md = `# MRP Requirement Gathering Report\n`;
        md += `Generated on: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}\n\n`;

        const priorityLabels = {
            'phase1': 'Phase 1',
            'phase2': 'Phase 2',
            'future': 'Future'
        };
        const formatPriority = (p) => priorityLabels[p] || String(p).toUpperCase();

        let overallTotal = 0;
        let overallScoped = 0;
        this.modules.forEach(m => {
            m.items.forEach(i => {
                if (i.suppressed) return; // Skip suppressed items
                overallTotal++;
                if (i.scope !== 'pending') overallScoped++;
            });
        });
        const pct = overallTotal > 0 ? Math.round((overallScoped / overallTotal) * 100) : 0;
        md += `## Progress Summary: **${pct}% Complete** (${overallScoped} of ${overallTotal} items scoped)\n\n`;

        md += `| Module | Total Items | Scoped Items | Completion | \n`;
        md += `| :--- | :---: | :---: | :---: | \n`;
        this.modules.forEach(mod => {
            const activeItems = mod.items.filter(item => !item.suppressed);
            const tot = activeItems.length;
            const scp = activeItems.filter(i => i.scope !== 'pending').length;
            const p = tot > 0 ? Math.round((scp / tot) * 100) : 0;
            md += `| ${mod.title} | ${tot} | ${scp} | ${p}% |\n`;
        });
        md += `\n---\n\n`;

        this.modules.forEach(mod => {
            md += `## ${mod.title}\n`;
            md += `*${mod.description}*\n\n`;

            const activeItems = mod.items.filter(item => !item.suppressed);
            const inScopeList = activeItems.filter(i => i.scope === 'in');
            const niceHaveList = activeItems.filter(i => i.scope === 'nice');
            const outScopeList = activeItems.filter(i => i.scope === 'out');
            const pendingList = activeItems.filter(i => i.scope === 'pending');

            if (inScopeList.length > 0) {
                md += `### In Scope\n\n`;
                inScopeList.forEach(item => {
                    md += `#### ${item.name} (Priority: ${formatPriority(item.priority)}, Criticality: ${(item.criticality || 'normal').toUpperCase()})\n`;
                    if (item.notes.trim()) {
                        md += `**Notes:**\n${item.notes.trim()}\n\n`;
                    } else {
                        md += `*No notes provided.*\n\n`;
                    }
                });
            }

            if (niceHaveList.length > 0) {
                md += `### Nice-to-Have\n\n`;
                niceHaveList.forEach(item => {
                    md += `#### ${item.name} (Priority: ${formatPriority(item.priority)}, Criticality: ${(item.criticality || 'normal').toUpperCase()})\n`;
                    if (item.notes.trim()) {
                        md += `**Notes:**\n${item.notes.trim()}\n\n`;
                    } else {
                        md += `*No notes provided.*\n\n`;
                    }
                });
            }

            if (outScopeList.length > 0) {
                md += `### Out of Scope\n\n`;
                outScopeList.forEach(item => {
                    md += `#### ${item.name} (Priority: ${formatPriority(item.priority)}, Criticality: ${(item.criticality || 'normal').toUpperCase()})\n`;
                    if (item.notes.trim()) {
                        md += `**Notes:**\n${item.notes.trim()}\n\n`;
                    } else {
                        md += `*No notes provided.*\n\n`;
                    }
                });
            }

            if (pendingList.length > 0) {
                md += `### Unassigned / Pending Items\n`;
                pendingList.forEach(item => {
                    md += `- **${item.name}**\n`;
                });
                md += `\n`;
            }

            md += `\n---\n\n`;
        });

        return md;
    }

    openExportModal() {
        const mdContent = this.generateMarkdown();
        this.exportPreviewContent.value = mdContent;
        this.exportModal.classList.add('open');
    }

    closeExportModal() {
        this.exportModal.classList.remove('open');
    }

    copyExportToClipboard() {
        this.exportPreviewContent.select();
        navigator.clipboard.writeText(this.exportPreviewContent.value)
            .then(() => {
                this.showToast("Copied to clipboard!");
            })
            .catch(err => {
                console.error("Failed to copy", err);
                alert("Failed to copy. Please copy the text manually from the screen.");
            });
    }

    downloadExportMarkdown() {
        const mdText = this.exportPreviewContent.value;
        const blob = new Blob([mdText], { type: 'text/markdown;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.setAttribute("href", url);
        link.setAttribute("download", "MRP_Requirement_Gathering_Report.md");
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        this.showToast("Markdown downloaded!");
    }

    exportCsv() {
        const headers = ["Module", "Item ID", "Item Name", "Scope Status", "Priority", "Criticality", "Notes"];
        const rows = [];

        const priorityLabels = {
            'phase1': 'Phase 1',
            'phase2': 'Phase 2',
            'future': 'Future'
        };

        this.modules.forEach(mod => {
            mod.items.forEach(item => {
                if (item.suppressed) return; // Skip suppressed items
                const scopeLabels = {
                    'in': 'In Scope',
                    'nice': 'Nice-to-Have',
                    'out': 'Out of Scope',
                    'pending': 'Unassigned'
                };
                const scopeStr = scopeLabels[item.scope] || item.scope;

                rows.push([
                    mod.title,
                    item.id,
                    item.name,
                    scopeStr,
                    (priorityLabels[item.priority] || item.priority),
                    (item.criticality || 'normal').toUpperCase(),
                    item.notes || ""
                ]);
            });
        });

        const escapeCsvCell = (cell) => {
            if (cell === null || cell === undefined) return "";
            let str = String(cell);
            str = str.replace(/"/g, '""');
            if (str.includes(",") || str.includes('"') || str.includes("\n") || str.includes("\r")) {
                str = `"${str}"`;
            }
            return str;
        };

        const csvContent = [
            headers.map(escapeCsvCell).join(","),
            ...rows.map(row => row.map(escapeCsvCell).join(","))
        ].join("\r\n");

        const blob = new Blob(["\ufeff" + csvContent], { type: 'text/csv;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.setAttribute("href", url);
        link.setAttribute("download", "MRP_Requirements_Export.csv");
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        this.showToast("CSV downloaded (Excel ready)!");
    }

    // JSON export
    exportJsonConfig() {
        const jsonString = JSON.stringify(this.modules, null, 4);
        const blob = new Blob([jsonString], { type: 'application/json;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.setAttribute("href", url);
        link.setAttribute("download", "ReqGather_Backup_Config.json");
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        this.showToast("JSON Config downloaded!");
    }

    // JSON Import
    triggerJsonImport() {
        this.importFileInput.click();
    }

    handleJsonImport(event) {
        const file = event.target.files[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = async (e) => {
            try {
                const importedData = JSON.parse(e.target.result);
                if (Array.isArray(importedData) && importedData.length > 0 && importedData[0].items) {
                    this.modules = importedData;
                    this.sanitizeData(this.modules);
                    await this.saveData();
                    this.renderCards();
                    if (this.activeModuleId) {
                        this.openDrawer(this.activeModuleId);
                    }
                    this.showToast("Configuration imported successfully!");
                } else {
                    alert("Invalid JSON format. Please upload a valid ReqGather backup config file.");
                }
            } catch (err) {
                console.error("Error reading JSON file", err);
                alert("Error parsing file. Please check that it is a valid JSON file.");
            }
        };
        reader.readAsText(file);
    }

    // Reset all data
    async resetAllData() {
        if (confirm("Are you sure you want to reset ALL data? This will clear all notes, scopes, priorities, and custom items, and restore default templates. This action cannot be undone.")) {
            if (!this.cryptoKey) return;
            try {
                const decryptedDefault = await decryptWithKey(ENCRYPTED_DEFAULT_MODULES, this.cryptoKey);
                localStorage.removeItem('mrp_requirements_data');
                this.modules = JSON.parse(decryptedDefault);
                this.sanitizeData(this.modules);
                await this.saveData();
                this.renderCards();
                if (this.activeModuleId) {
                    this.closeDrawer();
                }
                this.showToast("All data has been reset.");
            } catch (e) {
                console.error("Reset data decryption failed", e);
                this.showToast("Error resetting data.");
            }
        }
    }

    // Custom Module Modal methods
    openAddModuleModal() {
        this.inputModuleTitle.value = '';
        this.inputModuleDesc.value = '';
        this.addModuleModal.classList.add('open');
        setTimeout(() => this.inputModuleTitle.focus(), 100);
    }

    closeAddModuleModal() {
        this.addModuleModal.classList.remove('open');
    }

    async createCustomModule() {
        const titleText = this.inputModuleTitle.value.trim();
        const descText = this.inputModuleDesc.value.trim();
        if (!titleText) {
            alert("Please enter a module title.");
            return;
        }

        const newModule = {
            id: `module-custom-${Date.now()}`,
            title: titleText,
            description: descText || "Custom business module configuration.",
            icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 6.042A8.967 8.967 0 006 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 016 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 016-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0018 18a8.967 8.967 0 00-6 2.292m0-14.25v14.25" /></svg>`,
            items: []
        };

        this.modules.push(newModule);
        await this.saveData();
        this.closeAddModuleModal();
        this.showToast(`Module "${titleText}" created successfully!`);
    }

    async deleteCustomModule(moduleId) {
        const mod = this.modules.find(m => m.id === moduleId);
        if (!mod) return;

        if (confirm(`Are you sure you want to delete the module "${mod.title}" and all its requirements? This action cannot be undone.`)) {
            const index = this.modules.findIndex(m => m.id === moduleId);
            if (index !== -1) {
                this.modules.splice(index, 1);
                await this.saveData();
                this.closeDrawer();
                this.showToast(`Deleted module "${mod.title}"`);
            }
        }
    }

    // Setup Event Listeners
    setupEventListeners() {
        // Close drawer buttons
        this.btnCloseDrawer.addEventListener('click', () => this.closeDrawer());
        this.drawerOverlay.addEventListener('click', () => this.closeDrawer());

        // Escape key to close drawer/modals
        window.addEventListener('keydown', (e) => {
            if (e.key === 'Escape') {
                this.closeDrawer();
                this.closeExportModal();
                this.closeAddModuleModal();
            }
        });

        // Add custom focus area
        this.btnAddCustomFocus.addEventListener('click', () => this.addCustomFocus());
        this.inputNewFocusName.addEventListener('keydown', (e) => {
            if (e.key === 'Enter') {
                this.addCustomFocus();
            }
        });

        // Export Modal controls
        this.btnExportMd.addEventListener('click', () => this.openExportModal());
        this.btnExportCsv.addEventListener('click', () => this.exportCsv());
        this.btnCloseExportModal.addEventListener('click', () => this.closeExportModal());
        this.btnCopyPreview.addEventListener('click', () => this.copyExportToClipboard());
        this.btnDownloadPreview.addEventListener('click', () => this.downloadExportMarkdown());

        // JSON config controls
        this.btnExportJson.addEventListener('click', () => this.exportJsonConfig());
        this.btnImportJson.addEventListener('click', () => this.triggerJsonImport());
        this.importFileInput.addEventListener('change', (e) => this.handleJsonImport(e));

        // Reset
        this.btnReset.addEventListener('click', () => this.resetAllData());

        // Toggle suppressed items list
        this.suppressedHeader.addEventListener('click', () => this.toggleSuppressedList());

        // Add Custom Module Modal controls
        this.btnCancelAddModule.addEventListener('click', () => this.closeAddModuleModal());
        this.btnCloseAddModuleModal.addEventListener('click', () => this.closeAddModuleModal());
        this.btnConfirmAddModule.addEventListener('click', () => this.createCustomModule());
        this.inputModuleTitle.addEventListener('keydown', (e) => {
            if (e.key === 'Enter') {
                this.createCustomModule();
            }
        });

        // Authentication form & actions
        this.loginForm.addEventListener('submit', (e) => {
            e.preventDefault();
            this.handleLogin();
        });

        this.btnLogout.addEventListener('click', () => {
            this.handleLogout();
        });
    }

    // Authentication session check
    async checkAuth() {
        const creds = sessionStorage.getItem('reqGatherCreds');
        if (creds) {
            try {
                this.cryptoKey = await deriveMasterKey(creds);
                const decrypted = await decryptWithKey(ENCRYPTED_DEFAULT_MODULES, this.cryptoKey);
                document.body.classList.add('logged-in');
                this.loginScreen.style.display = 'none';
                await this.loadData(decrypted);
                this.renderCards();
                this.updateOverallProgress();
            } catch (e) {
                console.error("Session verification failed", e);
                this.handleLogout(false);
            }
        } else {
            document.body.classList.remove('logged-in');
            this.loginScreen.style.display = 'flex';
            setTimeout(() => {
                if (this.usernameInput) this.usernameInput.focus();
            }, 100);
        }
    }

    // Handle credential verification
    async handleLogin() {
        const username = this.usernameInput.value.trim();
        const password = this.passwordInput.value;
        const creds = `${username}:${password}`;

        try {
            const tempKey = await deriveMasterKey(creds);
            const decrypted = await decryptWithKey(ENCRYPTED_DEFAULT_MODULES, tempKey);
            this.cryptoKey = tempKey;
            sessionStorage.setItem('reqGatherCreds', creds);
            document.body.classList.add('logged-in');
            this.loginScreen.style.display = 'none';
            this.loginError.style.display = 'none';
            this.usernameInput.value = '';
            this.passwordInput.value = '';
            await this.loadData(decrypted);
            this.renderCards();
            this.updateOverallProgress();
            this.showToast("Welcome back!");
        } catch (e) {
            this.loginError.style.display = 'block';
            this.loginError.classList.remove('shake');
            this.loginError.offsetWidth;
            this.loginError.classList.add('shake');
        }
    }

    // Handle session end
    handleLogout(confirmLogout = true) {
        if (confirmLogout) {
            if (!confirm("Are you sure you want to log out?")) {
                return;
            }
        }
        sessionStorage.removeItem('reqGatherCreds');
        this.cryptoKey = null;
        document.body.classList.remove('logged-in');
        this.loginScreen.style.display = 'flex';
        if (this.activeModuleId) {
            this.closeDrawer();
        }
        this.showToast("Logged out successfully.");
        setTimeout(() => {
            if (this.usernameInput) this.usernameInput.focus();
        }, 100);
    }
}

// Initialise App on DOM Content Loaded
document.addEventListener('DOMContentLoaded', () => {
    window.app = new ReqGatherApp();
});
